### ISSUE TITLE
Unit tests and continuous integration

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#100]
We need to be more serious about testing and breaking stuff especially in core and engine as more people start to use it. Unit tests are the way to go.
- [ ] Write unit tests for core features
- [x]  Run a CI script daily on master

**Comment by nmellado** [comment]
FYI: 2 tests fail with VS2017: Geometry and String.

**Comment by nmellado** [comment]
Same problem with linux builds, but only in release mode (didn't try Debug mode with MS).

**Comment by louen** [comment]
Which tests are failing exactly ? I should have fixed at least one of these (the swing and twist)
