### ISSUE TITLE
.inl coding style

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#1011]
After some tests with [include what you use](https://github.com/include-what-you-use/include-what-you-use), I have trouble with .inl file inclusion.
I have checked google coding style and they do not recommend the usage of .inl files anymore (iwyu is a google tool).
Maybe we can also move .inl content to .hpp, then inclusion order for .inl is not important anymore.

The (only) drawback is to have bigger .hpp, but we can say all inline decl are at the end of file, and all class definition are at the beginning.

**Comment by MathiasPaulin** [comment]
I though we have discuss about that AFK. I'm fine with this (remove ".inl" files). 

We can do this progressively in the upcoming PRs. For each new class, use only .hpp and .cpp, for each modified class, remove the .inl file. Like this, everything will be done smoothly.

**Comment by dlyr** [comment]
Fine for me for the new class. I have also a script (wip) to do this automatically for old code.
