### ISSUE TITLE
Clarify build instructions for Windows/Visual Studio

### ISSUE THREAD

**Issue by ZaOniRinku** [STORM-IRIT/Radium-Engine#1051]
https://storm-irit.github.io/Radium-Engine/release-candidate/dependenciesmanagement.html#autotoc_md17
A subtitle should be added to clarify that the instructions using the _cmake_ CLI is for Linux only.

For Windows/Visual Studio, "Open external/CMakeLists.txt" is not clear enough (which is partially Visual Studio's fault) as it is not possible to open a CMakeLists file as a project from Visual Studio's launcher. The instructions should be:
- Click on "Continue without code"

<img width="762" alt="continuewithoutcode" src="https://github.com/STORM-IRIT/Radium-Engine/assets/20599684/b48fa34e-810b-4508-b4ac-a26fb4ef24f9">

- File > Open > CMake...

<img width="485" alt="fileopencmake" src="https://github.com/STORM-IRIT/Radium-Engine/assets/20599684/c69326c7-a203-4ac2-b8c4-e6175ad7f83d">

- Open external/CMakeLists.txt

https://storm-irit.github.io/Radium-Engine/release-candidate/basicsCompileRadium.html#autotoc_md15
A comma is missing after "QtDir": "C:/Qt/6.3.0/msvc2019_64/".
glfw does not come with the lib/cmake directory, either in source or binary form. To create it, download glfw sources from either the official website or GitHub, open the directory with Visual Studio and use Build > Install GLFW, it will create this directory in "out/install/x64-(Debug/Release)).

In "Execution of a demo app", "inheritEnvironments" should be "RadiumDllsLocations" instead of "RadiumDllLocations" (missing a "s" in "Dlls".

**Comment by dlyr** [comment]
Also externalDllsDIR miss some locations since external update `"ExternalDllsDIR": "${projectDir}/../radium-externals/install/${name}/bin;${projectDir}/../radium-externals/install/${name}/globjects;${projectDir}/../radium-externals/install/${name}/glbinding",`
