### ISSUE TITLE
Redundant code in entity / component creation

### ISSUE THREAD

**Issue by Zouch** [STORM-IRIT/Radium-Engine#112]
When creating an entity and a component, the code looks like 

```
Entity* entity = mgr->createEntity(name);
FooComponent* component = new FooComponent(name);
component->setEntity(entity);
entity->addComponent(component);
```

This could be factorized a little bit to make this less error prone by adding the entity to the component constructor or having `setEntity` (_resp._ `addComponent`) call `addComponent` (_resp._ `setEntity`)

**Comment by Zouch** [comment]
Actually, this is the same for `RenderObject`s and `Component`s.

**Comment by louen** [comment]
Currently Entity::addComponent calls component->setEntity(this).

**Comment by hoshiryu** [comment]
Ping: is this issue still topical?

**Comment by louen** [comment]
Let's say component creation could be better designed so that not all these function calls are necessary...

**Comment by MathiasPaulin** [comment]
In the code, there is :  
```
   /// Add a component to the given entity. Ownership is transfered to the component.
    void addComponent( Component* component );
```
Should we read 
````
    /// Add a component to the given entity. Component ownership is transfered to the entity.
    void addComponent( Component* component );
```

**Comment by MathiasPaulin** [comment]
Well ... actually, this is no longer topical. Component creation is simple : get or create the entity to which the component will be attached, create the component, add it to the entity. 2 lines if we do not take into account the entity fetch.
Simplifying the Component creation might rely on adding the entity the component belongs to as parameter of the component constructor. Creation will then be 1 line and ensure to establish the invariant on the component (it is attached to an entity). 
Seems to me that this is the god way to do that for component ...

For ```RenderObjects```this is already make. Constructor take the component as parameter.

**Comment by MathiasPaulin** [comment]
Fixed in new-filesystem branch - next stable release
