### ISSUE TITLE
Duplicate code for HalfEdge

### ISSUE THREAD

**Issue by Ana873331** [STORM-IRIT/Radium-Engine#120]
Core/Mesh/DCEL/HalfEdge
Core/Mesh/

**Comment by louen** [comment]
Related to #75

**Comment by nmellado** [comment]
New policy for this: the DCEL is going to be replaced by OpenMesh (see PR #200).
The other half-edge structure should be considered as deprecated and to be removed.

**Comment by MathiasPaulin** [comment]
Fixed by #364.
