### ISSUE TITLE
Ressource management : copying shader file in the install directory

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#155]
Copying the ressources of the application is a good thing when installing for production. nevertheless, when developping, this could generate problems with some of these resources, mainly shaders.
We have the common habits to edit the shader sources, modify and then reload and recompile the source. If we must manually manage the different versions of the shader (the ones in the debug, release, profile, .... build type directories) this will be verry error prone and dangerous. So, we must find a way to centralise all the ressources in one directory only, whatever the build type is.

**Comment by louen** [comment]
Isn't that already the case ? the shaders dir is not per build type afaik.

**Comment by MathiasPaulin** [comment]
The last  build System copy shaders in the Debug build or Release build dir etc ...
Nico we have verified this together.

**Comment by nmellado** [comment]
With the new version, shaders *are* copied in the bin dir, to have a self contained folder with a running app.

**Comment by louen** [comment]
OK. This is bad indeed. A better solution would be to change the default shader directory to point to the unique version.

**Comment by nmellado** [comment]
How to you generate a self-contained folder with all the required asset in that case ?

**Comment by louen** [comment]
why would you need that ?

**Comment by nmellado** [comment]
to publish releases

**Comment by MathiasPaulin** [comment]
In that case, why not just copy the ressources in the "install" target or whatever the name we could imagine for the publication of a standalone executable.

**Comment by nmellado** [comment]
this can be done, but don't forget that we need to be sure the right relative paths (to the shaders) will be used in the C++ applications code.

**Comment by louen** [comment]
This could be configurable by the command line with sensible default arguments

**Comment by nmellado** [comment]
which command line, run or compile ?
This can also be configured with cmake, depending on the target (normal or release)

**Comment by dlyr** [comment]
And I think it's application related, should be defined in CMakeLists.txt of the application

**Comment by nmellado** [comment]
Except that some shaders are hard-linked in Radium's core...

**Comment by nmellado** [comment]
This has been fixed by using symlinks on linux/macos, and by copying the shader directory on windows.
