### ISSUE TITLE
Investigate cotire to reduce compilation time

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#172]
**Cotire** (https://github.com/sakra/cotire) is an automatic CMake script which enables option to reduce compilation time such as  pre-compiled headers.
We could try to adapt it to Radium to see if it works.

**Comment by nmellado** [comment]
A simpler option would be to precompile once for all the Eigen types that are mostly used in Radium.
This would not save as much time as Cotire, but it's a single file to create (explicit specialization in one of the Radium's core file.

**Comment by louen** [comment]
This doesn't affect the problem of the massive Eigen headers being included everywhere though

**Comment by MathiasPaulin** [comment]
From my experience gained while integrating glbinding, we could first remove the huge number of non necessary inclusions everywhere in the code to keep compilation time quite acceptable. I'll have a look on Cotire neverteheless.
