### ISSUE TITLE
Camera management : automatic and optimal znear/zfar

### ISSUE THREAD

**Issue by matthieu-locussol** [STORM-IRIT/Radium-Engine#181]
I've found a little bug when playing around with the Radium's MinimalApp.

When you replace the shader used by the MinimalComponent (BlinnPhong) by any other shader (Default for example), the spinning cube is blinking dark.

![bug](https://cloud.githubusercontent.com/assets/7999777/24757543/d3b542ba-1adf-11e7-8692-a360948e8f11.png)

**Comment by Jeckhys** [comment]
This may come from the near and far planes values

**Comment by louen** [comment]
Can you explain the mechanism of the Vortex Engine you are refering to ?

**Comment by dlyr** [comment]
compute the near and far plain depending on the sphere bounding box (hence maximizing the z precision).
This should be done by default and user controllable (for instance when one want to draw something out of the scene list or in screen space).

**Comment by nmellado** [comment]
Is this still true ?

**Comment by MathiasPaulin** [comment]
Yep, this is still true. Actually, znear/zfar is set to 0.1/1000.0 that is a very bad idea for small scenes.
Only the CameraInterface manipulates the Znear/Zfar and they are constant.
I push this issue up, it is quite easy to fix knowing the aabb of the scene.

**Comment by nmellado** [comment]
Is this still true ?

**Comment by MathiasPaulin** [comment]
Yep, this is still true. I'll do that this week (before 10/09/2018 :p)

**Comment by MathiasPaulin** [comment]
The branch fix_issue#181 updates the camera z-near/zfar at each frame. Works well but unwanted side effects appear (clipping of ui objects and debug objects to the scene bounding box) due to the way the rendering is done. Must find a workaround or wait for Radium v2 (dedicated to rendering) to integrate this.

**Comment by nmellado** [comment]
@MathiasPaulin there is a branch calles `fix_issue#181` (https://github.com/STORM-IRIT/Radium-Engine/tree/fix_issue%23181) in which you contributed.
Shall we consider picking the changes you made by this time ?

**Comment by MathiasPaulin** [comment]
@nmellado The branch called `fix_issue#181` defined a solution for this issue but there were problems integrating this solution due to the way camera are managed. I'll give a look quickly to propose a better solution.

**Comment by nmellado** [comment]
Ok.
Keep in mind there is also the issue #459 open regarding camera management.

**Comment by nmellado** [comment]
@MathiasPaulin what is the status of this issue (I ask as you were the last involved)

**Comment by MathiasPaulin** [comment]
Issue is still here. No time yet to fix it efficiently.

**Comment by nmellado** [comment]
No problem, I 've re-opened the issue.
