### ISSUE TITLE
Adding light to renderer [compliance to MVC]

### ISSUE THREAD

**Issue by Jeckhys** [STORM-IRIT/Radium-Engine#182]
The only way I found to add a light to the renderer in my application is first to get the renderer from the viewer and then use its addLight() method.
The first point here is that I have to give non-const access to the renderer through the viewer.
The second point is that the renderer may not be accessed through the View but through the Model.

**Comment by nmellado** [comment]
@Jeckhys is this fixed ?

**Comment by Jeckhys** [comment]
The first point is kind of fixed since I added a method to get a non-const renderer from the viewer, but I didn't do anything to fix the second point. I don't know how it should be re-implemented in order to have a more MVC pattern compliance.

**Comment by louen** [comment]
I think lights should be added to the scene somehow
There could be a Light Component added to the default system entity (entity 0) which would allow us
to display a render object to represent the light

**Comment by MathiasPaulin** [comment]
this is fixed in PR Code style refactoring #299
