### ISSUE TITLE
ShaderConfiguration - DefaultShader does not exist

### ISSUE THREAD

**Issue by Jeckhys** [STORM-IRIT/Radium-Engine#198]
A default shader configuration has been introduced since this commit : 

https://github.com/AGGA-IRIT/Radium-Engine/commit/59b54d242b56f21f9711b120219aa5d95da67b7a#diff-2a234226723ed7563d8e4a151b87864e

The shader source files do not exist (no "DefaultShader.*.glsl").

We should either create DefaultShader.*.glsl or replace "DefaultShader.*.glsl", in ShaderConfiguration.cpp at lines 146 & 147, with "Default.*.glsl"

By the way, this should be "Shaders/DefaultShader.*.glsl".

**Comment by nmellado** [comment]
As you can see here, this shader is directly included in the source code: https://github.com/AGGA-IRIT/Radium-Engine/commit/59b54d242b56f21f9711b120219aa5d95da67b7a#diff-2a234226723ed7563d8e4a151b87864e

**Comment by hoshiryu** [comment]
Ping: is this issue still topical?

**Comment by nmellado** [comment]
Fixed by #199
