### ISSUE TITLE
Mesh Management

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#202]
There is some common agreement on the need to erase the FancyMesh plugin and replace it with a proper and nicer mesh management.
Also, there is some considerations about where stuff like texture coordinates, tangent, bitangent and others should be stored.

## Current State

For now, when loading a mesh, the loader gives a FileData to the Engine that calls for the system to handle it.
In particular, the system of the FancyMesh plugin use the GeometryData to build one FancyMeshComponent per mesh for visualization purposes:
* the TriangleMesh is embedded inside an Engine::Mesh, managing OpenGL memory consistency;
* this Engine::Mesh is stored in a RenderObject through a shared_ptr, along with the material and shader config;
* the FancyMeshComponent give read/write access to the TriangleMesh via the ComponentMessenger.
For the RenderObject to take into account modifications made on the mesh by other components (such as the SkinningComponent), the "dirty" flag is set, for the corresponding data, by the FancyMeshComponent when the write-access getter is called via the ComponentMessenger.
Also to be noted, there is a never-used method in RenderObject to create one from a GeometricData.

Regarding the geometry data, the only ones stored in the TriangleMesh are the vertices, the per-vertice normals and the triangles (vertices indices). Texture coordinates, tangent and bitangent vectors, and other vertex-wise attributes (not talking about skinning weights here) are stored by the Engine::Mesh.
Also to be noted, for now there can be only one attribute of a kind.

## Issues with the current state

For now, the one owning the TriangleMesh is the FancyMeshComponent, but through the Engine::Mesh used by its RenderObject.
Therefore, the FancyMesh plugin is for now mandatory to have a mesh to work on, which breaks the concept of plugin and which may lead to undesired code structure and complexity in some cases.

Regarding the geometric data, having them split into the TriangleMesh and the Engine::Mesh causes an over-complex structure of the code for geometric treatment algorithms, which would depend on the Engine part of Radium, which is non-sense.

For example, in order to develop a mesh processing application that may be run without any visualization requirement (e.g. command-line tool), one may need to build its own geometric component owning the TriangleMesh.
Moreover, the TriangleMesh class is not self-sufficient for some treatment targeting or dependent on additional vertex-wise (or even triangle-wise) attributes, and a separate class have to be built.

## Possible Solutions

Regarding the geometric data storage, one solution is to pack all of them in a Core::Mesh class. This class would separate into TriangleMesh and PolygonMesh, and interfaced with OpenMesh to ease the development of geometry treatment algorithms (such as decimation, subdivision, curvature computation...).
Also, some improvements are required to handle multiple attributes of a kind.
By the way, rendering data such as the material may not be stored within the GeometricData.
Finally, as induced by issue #90, should the skinning weights be part of the GeometricData?

Regarding the FancyMesh plugin, I suggest to:
* add an util function in Core to build a Core::Mesh from a GeometricData;
* remove the afore-mentioned never-used RenderObject method;
* add a GeometricComponent in Engine owning the Core::Mesh and giving access to it through the ComponentMessenger;
* move the FancyMeshComponent from the plugin into Engine::Renderer, it would ask the ComponentMessenger for the Core::Mesh to initialize/update the RO;

For the visualization to update with respect to the modifications undergone by the Core::Mesh (such as geometric treatment and skinning), the question is still open.

**Comment by louen** [comment]
I agree we need a few refactoring in this regard. 

The current state of `Engine::Mesh` vs `TriangleMesh` is bad design. Especially because we sometimes abuse `TriangleMesh` to render line meshes. This is truly a bad design choice and needs to be fixed.

I want to keep `TriangleMesh` as simple as possible : points, normals and triangles. 
There definitely needs to be a `PolygonMesh` with N-sided faces instead of triangles (which also would work for line meshes I guess). Avoiding unnecessary copies and conversions is tricky though. Maybe it can be templatized ? I'm not sure.

The `Core::Mesh` you propose needs to have maybe a more explicit name (`DecoratedMesh` or `DisplayMesh` ?)

About your proposed solutions :
> add an util function in Core to build a Core::Mesh from a GeometricData;

Yes. Actually I just wrote the same thing for animation (PR incoming soon™)

> add a GeometricComponent in Engine owning the Core::Mesh and giving access to it through the ComponentMessenger;

Yes

> move the FancyMeshComponent from the plugin into Engine::Renderer, it would ask the ComponentMessenger for the Core::Mesh to initialize/update the RO;

Or just get rid of FMC for ever, and turn it into a collection of utlity methods to allow any component to have a proper display mesh ?

**Comment by hoshiryu** [comment]
About the `Engine::Mesh` vs `TriangleMesh`, the thing is that the `TriangleMesh` should store all the geometric data, or we would have another class as an extension of the basic data, and then adapt the `Engine::Mesh` to handle the extensions (but it seems too much boresome and inefficient).

>  Maybe it can be templatized ? I'm not sure.
I thought about it but it doesn't seem to be a good idea, since quad meshes may have triangles.

> The Core::Mesh you propose
Actually, it's already there

Ok for FMC, that's more or less the philosophy I was thinking of.

Still the main issue remains the update of the render mesh with respect to modifications of the geometric mesh

**Comment by louen** [comment]
> add an util function in Core to build a Core::Mesh from a GeometricData;

Actually this function should be part of Asset, not Core. See pr #205 for the Animation equivalent.

**Comment by nmellado** [comment]
That's really great @dlyr if you work on this. I can give a hand if needed.

I also push the idea that having a mesh and ways to store attributes (normals, colors, etc') using only the Radium Core library is mandatory if we want to open the code to geometry processing algorithms.

We also need to discuss how to handle properly pont clouds, lines, etc. I'm fine with having all this stored as a mesh as it is today (even though the classe name is misleading). @louen, as far as I understood, you don't seems happy with that, can you elaborate ?

**Comment by dlyr** [comment]
The refactoring first step is almost done. 
I have one concern with FancyMesh, I think we could change FancyMesh as something like MeshInstanciator (temp name).
The purpose of FancyMesh is to take a GeometryData, initialized from a file asset, and build a Mesh (temp name, maybe RenderMesh or EngineMesh), add the correct attrib and materials
The EngineMesh create a CoreMesh from this data.

The idea I have is that FancyMesh should be easily superseed to handle specific EngineMesh attribs, but only one FancyMesh like instance should be used to load a file at a time. Not sure what is the right way to manage this regarding plugins mechanism.

So if ok, after first step, I could check.

**Comment by nmellado** [comment]
> The idea I have is that FancyMesh should be easily superseed to handle specific EngineMesh attribs, but only one FancyMesh like instance should be used to load a file at a time.

As far as I understand, this stays true as long as the `MeshInstanciatorXXXX` classes still follow the `Component` and `System` pattern. The only difference is that these component would not be generated by the plugin mechanism, but rather by the application directly.

**Comment by dlyr** [comment]
Resolve in progress in #454

**Comment by dlyr** [comment]
Fixed by #454
