### ISSUE TITLE
Automatic timer data for frames

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#21]
- ~~Keep track of the time of each frame and display it on the main window~~
- Keep track of each task's timing and display it in in a neat way.

**Comment by Zouch** [comment]
Second point might be a great L3 project.

**Comment by hoshiryu** [comment]
Ping: is this issue still topical?

**Comment by MathiasPaulin** [comment]
re-Ping ???

**Comment by nmellado** [comment]
Question: what are the difference(s) between point 1 and 2 ? And then, do we really need this ?

**Comment by louen** [comment]
Ok, so now the task timings are outputted on stdout in a JSON-like format. 
Point 2 was actually an idea of a lightweight app which would analyze this data and show it in a nice way (e.g. with a timeline)

**Comment by nmellado** [comment]
Ok. 
for me, Point 2 is interesting but very very low priority. As suggested, it can be a fun student project, however I don't think the engine is stable enough for this.

**Comment by MathiasPaulin** [comment]
Were are we concerning this issue ? Is it still unsolved ?
