### ISSUE TITLE
OBJFileManager and others

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#211]
Once the pr #209 is accepted, it would be nice to adapt the OBJ/OFF/MAP FileManagers to the IO design.
Hence, adding a FileExporterInterface and split the FileManagers into a FileLoader and a File Exporter might be a good thing.

**Comment by louen** [comment]
I will add that I tried recently to export a collada file of a rigged mesh with assimp and it never worked. So in the meantime these simple exporters at least make something that works...

**Comment by nmellado** [comment]
We need them for point-cloud as well, Mathias needs them for rays and PBRT, etc..

**Comment by nmellado** [comment]
FYI: I have created the branch `io-tinyplyloader` (PR will come soon) to add a minimalist ply point cloud loader.
This could be an example to ease the adaptation of the aforementioned loaders

https://github.com/AGGA-IRIT/Radium-Engine/tree/io-tinyplyloader

**Comment by MathiasPaulin** [comment]
OBJ/OFF/MAP FileManagers are deprecated and will not be supported. New IO mechanism will be extended to exporter in Radium V2.
