### ISSUE TITLE
Ligths Management

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#212]
In the current state, when loading lights, the LightData structure is filled with the corresponding Engine::Light which stores the corresponding data. Hence, IO is dependent on Engine, which is not good.
A better architecture would be to move the Lights in Core, add parameter packs for each type in the LightData to be filled at load, and let the Renderer build the Lights from the LightData.

Also, since there is a need for some helper functions to create data from the Assets structures (meshes -- #202 , skeletons -- #205 ...), doing so also for the lights could be convenient.

**Comment by MathiasPaulin** [comment]
Integrated in branch master-v1. Lights are components, thereis a LightData in the Core/File.
This issue was closed by pr #299.
