### ISSUE TITLE
Test Radium Engine in a non-QT context

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#218]
It would be nice to try to write an app with glfw or equivalent.

In theory the Engine is independent of the application/UI library on top of it, but this remains to be proven. We might expose and fix a few hidden dependencies in the process.

Using a lightweight lib for the app/UI part (e.g. glfw / ImGui or nanoGui) would be a good starting point for small demo players or viewers.

**Comment by louen** [comment]
Ok, this is actually much simpler than I expected. I was able to make a GLFW version of the spinning cube demo in about 200 lines of code, without changing the engine code. So our design is not so crappy after all :)

**Comment by nmellado** [comment]
I've put this code in PR #222

**Comment by nmellado** [comment]
This has been done here: https://github.com/STORM-IRIT/Radium-NanoGUIApp
Closing.
