### ISSUE TITLE
Access renderer from a plugin

### ISSUE THREAD

**Issue by aarezou** [STORM-IRIT/Radium-Engine#219]
I did not find a way to access a renderer from a plugin (or the other way around).

if a pointer to the MainWindow is accessible, then `getViewer()->getRenderer()` will probably work, but I could not do that either.

**Comment by louen** [comment]
As said in the chat I think the easiest solution is to add the Viewer or the Renderer in `PluginContext` and grab it from your plugin.

**Comment by nmellado** [comment]
Fixed in #233
