### ISSUE TITLE
Asynchronous tasks

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#24]
We'd like to still be able to interact with the scene (e.g. move the camera) even with time consuming tasks. So we should not wait for all tasks to finish and actually skip a frame.

**Comment by Zouch** [comment]
Need synchronous (which we wait for) and asynchronous (which we don't wait) tasks.

**Comment by louen** [comment]
So, my current idea for async tasks is for the task queue to offer an API similar to synchronous tasks.
- An async task can depend on one (or several) sync tasks before being launched.
- An optional callback function will be called when the async task finished.
