### ISSUE TITLE
Could not create command line app using plugins with "interface"

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#253]
Some Plugins define a ui (e.g. Animation)
But when trying to implement a commandline app (without UI nor QApplication, just a QCoreApplication) I get the message :
`QWidget: Cannot create a QWidget without QApplication`
Could we think of a process to have plugins without UI, along with UI plugins that define UI only ?
Or at least delegate the UI setup to a specified method call by the mainapp if needed.

**Comment by louen** [comment]
I think the plugins should not create any widget in their constructor (as the `AnimationPlugin` does right now).

We can decide to do it in `registerPlugin` (in that case, we should tell the plugin if the application is command-line based  or gui-based in the `PluginContext`).
Or we can require that plugins create widgets lazily, i.e. only in when the `getWidget()` method is called.

Anyway, as a temporary workaround, with the current `mainApp`, you can either specify  which plugins you want loaded (`-l Plugin1 -l Plugin2`) or exclude some plugins (`-i Plugin3`).

**Comment by hoshiryu** [comment]
Since plugins are based on Qt, command-line based applications will need Qt to load them (may them have UI or not).

About creating widgets lazily, some plugins may want to change the widget state according to the selection that's made in the mainApp.

**Comment by MathiasPaulin** [comment]
One thing we could do is, in the same way openGL is managed with plugins, is to call all Qt dependent plugin functions only once the application using the plugin is able to receive its widget, actions ...
We do that for OpenGL : we call openGL plugin initialization only when OpenGL is initialized. 
Plugins Developper must be informed that registerPlugin() must initialize only what is mandatory for the plugins internal but not the UI or OpenGL services the plugin exposes. These must be initialized only in the corresponding Plugin entry points (e.g. getWidget, getMenu, getAction, getFeatureTrackingWidget and openGlInitialize for the moment).
