### ISSUE TITLE
Qt Event order and default viewport management (Viewer.cpp)

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#261]
On MacOs, no need to define the initial viewport, as written in the glviewport documentation :
"When a GL context is first attached to a window, width and height are set to the dimensions of that window. [(glViewport.xhtml)](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glViewport.xhtml)
INFORMATION FOR MACOS WITH RETINA : on retina screens, the (QWindow) window report a size of wxh and the initial viewport of size of 2wx2h.
It seems that this is not the case on Linux, where the (QWindow) window report a size of wxh and the initial viewport of size of 100x100. (at least on my Nvidia OpenGL 4.4 drivers)
So we set here the initial viewport to the size of the window.
Surprisingly, on MacOs, the wiewport follow the size of the window (I presume, as a consequence of the activation of the context by m_context->makeCurrent(this);). 
Not on Linux ... is it a Qt bunctionnality ?
More,  Qt event order are not the same on Linux, Windows and MacOs. This requires to put guards on event management method to be sure that all is correctly initialized.

**Comment by nmellado** [comment]
Can we close this ?

**Comment by MathiasPaulin** [comment]
yes
