### ISSUE TITLE
Unable to have OpenGL dependent initialization in a plugin on Linux (at least)

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#265]
When a main-app plugin needs to access OpenGL context or Radium objects that are created only after the OpenGL context, the plugin crash (e.g. when request ShaderManager instance).
On MacOs, all is fine due to the order the qt events are managed and when a plugin is loaded, access to the above mentioned OpenGL stuff is OK.
On Linux, the plugin segfault and cause the application to crash.
To solve that, we need to signal the plugin OpenGL is initialized in order to let him initialized its OpenGL dependent functionalities.
I propose to add to the plugin interface such a mecanism and let the application signal all pugins that has an OpenGL Initializer when the application receive the glInitialized signal.
Are you agree ?

**Comment by nmellado** [comment]
This is related to the way we add renderers from plugins in MainApplication.

I guess this signal could also transmit an EnginePluginContext containing the Engine and other needed information.
We could have a doNeedGL in plug-ins, and handleGLInit( EnginePluginContext& context).
This would remove the redundant addrenderer function

**Comment by MathiasPaulin** [comment]
addRenderer function will not be redundant (e.g, a ray-tracing based renderer will not need opengl initialization.
What I planned is to have an "hasInitilizerOpenGL" (that default to false and an "InitilizeOpenGl" that will take the openGL context (as well as the Ra::PluginContext as parameter that plugin may implement.

**Comment by nmellado** [comment]
Right now we can’t have a renderer without GL.
So, I don’t know. It’s just that the plugin Interface is being more and more messy.

**Comment by MathiasPaulin** [comment]
For the moment, we don't but I'm writing one ... (with Master students).
And, for now, I've plugin that extends the material subsystem (and then ShaderManager and so on) without adding a new renderer thanks to the modification I made in the material_subsystem2 branch.

**Comment by MathiasPaulin** [comment]
Plugin Interface is not so messy but could be clarified in a second time in order to separete different typ of plugins. If a plugin then need to add renderer, OpenGL stuff, action, menu, widget ... it will implement several interfaces ... The easier way before separating plugin interface is to continue in the same spirit that the actual plugin interface and if refactoring become mandatory, we will see at usage.

**Comment by nmellado** [comment]
Ok, go head then.

**Comment by nmellado** [comment]
Can we close this ?

**Comment by MathiasPaulin** [comment]
yes
