### ISSUE TITLE
main-app "Clear scene" segfault or make the application chaotic

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#266]
on branch master, when pushing the button "Clear scene" when the scene is empty or when no scene is selected segfault.
When the scene is not empty, remove more than the scene : the "Test" object that is marked as 
```// FIXME (Florian): this should disappear``` 
and the FeatureTrackingEntity that appear in the Engine Objects Tree are removed.
The, the application crash at the next operation ...

**Comment by nmellado** [comment]
Can we close this §

**Comment by hoshiryu** [comment]
Crash still there!

**Comment by hoshiryu** [comment]
Fixed by PR #269 , closing!
