### ISSUE TITLE
Radium Compilation Options

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#274]
Currently I am using a specific cmake setup for the compilation of the Radium-Engine and our team-specific plugins so that these plugins access the Radium-Engine cmake options.
The setup is as follows (from directory "project"):
 * a Radium-Engine subdir cloned from the github,
 * a Radium-Engine-Plugins subdir for the team-specific plugins,
 * a CmakeLists.txt file adding the two latest as subdirectories.

While the Radium-Engine cmake build chain is not designed to support such a setup, it's the easiest way to have the Radium-Engine cmake options apply on the other plugins.
However, doing this I have to compile the Radium-Engine first (either directly by ignoring the cmake warnings about "radium libs not found", or from another build directory so that cmake can find them later), then rerun cmake to find the newly built radium libs, and finally build the other plugins.
For further compilations of modifications of either the Radium-Engine or the other plugins, compiling just once is enough though.

I do think that a way to give access to the Radium-Engine cmake options can be a good thing, even more if want to get the corresponding compilation flags from the "CompileFlags.cmake" file.

A way to do so would be for the Radium-Engine's cmake run to build a "CmakeOption.cmake" file in the bundle directory and then to load it (if present) in the "FindRadium.cmake" file.

Regarding the compilation, we could decide to let other project have such a cmake setup, in which case we must:
 * ensure the options are not loaded twice,
 * check in the "FindRadium.cmake" file if the radium libs are current cmake targets if they have not been found.

**Comment by nmellado** [comment]
Your setup is not following the cmake guidelines.

A proper way to do this would be to use [ExternalProject](https://cmake.org/cmake/help/git-master/module/ExternalProject.html#module:ExternalProject) instead of [add_subdirectory](https://cmake.org/cmake/help/git-master/command/add_subdirectory.html).

Indeed, as you want to use the same options between different projects, you need to define these options in your head/master project, and propagate them in the child projects.
Following this idea, your head project file would look like (disclamer: this code has not been tested):
``` cmake

# Expose some options to the user
option(MY_WITH_OMP              "Use OpenMP" ON)
option(MY_WARNINGS_AS_ERRORS    "Treat compiler warning as errors" ON)
option(MY_ASSIMP_SUPPORT        "Enable assimp loader" ON)
option(MY_TINYPLY_SUPPORT       "Enable TinyPly loader" OFF)
option(MY_BUILD_APPS            "Choose to build or not radium applications" ON)
option(MY_FAST_MATH "Enable Fast Math optimizations in Release Mode (ignored with MVSC)" OFF)

# add Radium with the options you want to override
ExternalProject_Add(
        Radium
        # where the source will live
        SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Radium-Engine"
        # set the compilation options
        CMAKE_ARGS
            -DRADIUM_WITH_OMP=${MY_WITH_OMP}
            -DRADIUM_WARNINGS_AS_ERRORS=${MY_WARNINGS_AS_ERRORS}
            -DRADIUM_ASSIMP_SUPPORT=${MY_ASSIMP_SUPPORT}
            -DRADIUM_TINYPLY_SUPPORT=${MY_TINYPLY_SUPPORT}
            -DRADIUM_BUILD_APPS=${MY_BUILD_APPS}
            -DRADIUM_FAST_MATH=${MY_FAST_MATH}
            -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
            -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
)

# add Radium with the options you want to override
ExternalProject_Add(
        Radium-Plugin1
        # where the source will live
        SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Radium-Plugin"
        # set the compilation options
        CMAKE_ARGS
            -DRADIUM_WITH_OMP=${MY_WITH_OMP}
            -DRADIUM_WARNINGS_AS_ERRORS=${MY_WARNINGS_AS_ERRORS}
            -DRADIUM_ASSIMP_SUPPORT=${MY_ASSIMP_SUPPORT}
            -DRADIUM_TINYPLY_SUPPORT=${MY_TINYPLY_SUPPORT}
            -DRADIUM_BUILD_APPS=${MY_BUILD_APPS}
            -DRADIUM_FAST_MATH=${MY_FAST_MATH}
            -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
            -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
)

add_dependency (Radium-Plugin1 Radium)
```
Then, in your plugin, you can use Radium's `CompileFlags.cmake`, as you have the proper options.

**Comment by hoshiryu** [comment]
Ok, did it as you proposed and it worked fine (had to do some changes and thus I updated your above code).

**Comment by hoshiryu** [comment]
There is still an issue with this setup: qtcreator only loads headers in the project tree view...

**Comment by nmellado** [comment]
This issue is related to https://github.com/STORM-IRIT/Radium-Engine/projects/2#card-7560506
