### ISSUE TITLE
Picking not available on MacOs and Windows

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#295]
Due to problem when rendering in picking mode, picking is not functionnal on MacOs and is quite hazardous on windows.
Picking texture, as displayed in the main app for instance, is always -1 (the initial value) whatever the picking mode or object.

**Comment by hoshiryu** [comment]
can you test PR #298 on mac?

**Comment by MathiasPaulin** [comment]
Tested .. Picking now works.
But I don't understand why culling causes no fragment written in the output. Need to investigate what are the values of in_position, in_eye and in_normal and why the dot product is always negative (note that you do not need to normalize as only the sign matters).

**Comment by hoshiryu** [comment]
Fixed by #298 , closing
