### ISSUE TITLE
Radium Core refactoring: call for participation

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#302]
As mentioned in the [Radium Stable Release project ](https://github.com/STORM-IRIT/Radium-Engine/projects/2) , we need to simplify Radium's **Core** package.
This issue is expected to be a discussion leading to the final design of the Core package.

Looking at the directory structure (we assume `master-v1` as a basis), I'm proposing the following changes (for the sake of clarity, folders and files are named relatively with `Core/`, e.g., `Animation`,`Animation/Handle` and `RaCore.hpp`):

- We keep 6 main folders:
  - `Animation`: no change with the current version
  - `Asset`: former `File` folder
  - `Container`: former `Containers` folder
  - `Geometry`: contains former `Geometry`, `Mesh` and `Algorithm` folders (see below)
  - `Math`: no change with current version
  - `Utils`: current folder + other utility classes (see below).
- We move
  - `Algorithm` as `Geometry/Algorithm`: because it contains only algorithms related to geometry
  - `Event` to `../GuiBase`
  - `Index/*` into `Container`
  - `Log/*`, `String/*` and `Time/*` into `Utils/`
 - We use the official 3rd party repository for `stb_image`: https://github.com/nothings/stb

All the folders containing namespace function would also be removed, e.g., `String/StringUtils.hpp` would become `Utils/StringUtils.hpp`, and not `Utils/String/StringUtils.hpp`.

Open questions:
 - Is the `Task` system part of the `Core` or `Engine` package ? If it's in the `Core`, do we have all the necessary classes in this package to manage and use tasks without `Engine` and `GuiBase` ?
 - The `TreeStructure` folder could be moved either into `Geometry` or `Containers`. As for me both would make sens, I'm expecting you some comments about this.
 - There is a lot of redundant code related to topological mesh representation and processing. As `TopologicalMesh` will be the next standard, all other representations and algorithms using them will be removed. **If you use adjacency or DCEL-related data-structures or algorithms**, you must express your needs here so we can adapt the `TopologicalMesh` ecosystem.
 - There is a lot of namespace functions in the existing `Geometry` folder. I suggest we move them as much as possible into their related classes. Please also express your needs here if you are currently using this.

**Comment by hoshiryu** [comment]
I agree with the directory structure changes you propose.
Regarding the `Task` system, having it in `Core` allows to build Core-dependent only apps that use independent tasks, though I don't have any example in mind. And yes, we have all we need for those.
Regarding the `TreeStructure`, I would rather put it in Geometry, and keep Containers for vectors and grids which are actual data containers.
Finally, for the `TopologicalMesh` ecosystem, It would be nice to consider the possibility to have subdivision as a post-process done right before the rendering (during the Core to GL routines?), and so even on animated meshes.
For the subdivision, I am currently using a CPU CatmullClark scheme (based on `HalfEdgeData`) performed on the polygonal faces of the (modified) TriangleMesh. Just applying tesselation through the shaders might be enough, though I don't know how nice the results are w.r.t. the mesh polygonisation.

**Comment by dlyr** [comment]
So here is the current directory strcuture
```
./Algorithm
./Algorithm/Delta
./Algorithm/Diffusion
./Algorithm/HeatDiffusion
./Algorithm/ScalarField
./Algorithm/Smoothing
./Algorithm/Subdivision
./Animation
./Animation/Handle
./Animation/Pose
./Animation/Sequence
./Animation/Skinning
./Containers
./Event
./File
./File/deprecated
./File/KeyFrame
./Geometry
./Geometry/Adjacency
./Geometry/Approximation
./Geometry/Area
./Geometry/Curvature
./Geometry/Distance
./Geometry/Laplacian
./Geometry/Mapping
./Geometry/Normal
./Geometry/Partition
./Geometry/PointCloud
./Geometry/Segment
./Geometry/Triangle
./Image
./Index
./Log
./Math
./Mesh
./Mesh/DCEL
./Mesh/DCEL/Iterator
./Mesh/DCEL/Iterator/Edge
./Mesh/DCEL/Iterator/Face
./Mesh/DCEL/Iterator/Vertex
./Mesh/DCEL/Operations
./Mesh/TopologicalTriMesh
./Mesh/TopologicalTriMesh/Operations
./Mesh/Wrapper
./String
./Tasks
./Time
./TreeStructures
./Utils
./Utils/Graph
```

If I undestand well the new one will be 
```
./Animation
./Animation/Handle
./Animation/Pose
./Animation/Sequence
./Animation/Skinning

./Asset
./Asset/deprecated
./Asset/KeyFrame

./Container

./Geometry
./Geometry/Adjacency
./Geometry/Approximation
./Geometry/Area
./Geometry/Curvature
./Geometry/Distance
./Geometry/Laplacian
./Geometry/Mapping
./Geometry/Normal
./Geometry/Partition
./Geometry/PointCloud
./Geometry/Segment
./Geometry/Triangle

./Geometry/Algorithm
./Geometry/Algorithm/Delta
./Geometry/Algorithm/Diffusion
./Geometry/Algorithm/HeatDiffusion
./Geometry/Algorithm/ScalarField
./Geometry/Algorithm/Smoothing
./Geometry/Algorithm/Subdivision


./Geometry/Mesh
./Geometry/Mesh/DCEL
./Geometry/Mesh/DCEL/Iterator
./Geometry/Mesh/DCEL/Iterator/Edge
./Geometry/Mesh/DCEL/Iterator/Face
./Geometry/Mesh/DCEL/Iterator/Vertex
./Geometry/Mesh/DCEL/Operations
./Geometry/Mesh/TopologicalTriMesh
./Geometry/Mesh/TopologicalTriMesh/Operations
./Geometry/Mesh/Wrapper

./Utils
./Utils/Graph

./Tasks

#what about theses
./Image
./Math
```
I would prefer something like 
```
./Animation
./Asset
./Container
./Geometry
./Utils
./Tasks
```

**Comment by hoshiryu** [comment]
From what I understood, `Image` will be a sub-module, `Math` will be a directory under `Core` (as ./Math), and `Tasks` will go into `Utils` (if we consider it should stay in `Core`).
What is the difference with the last structure you mentioned?

**Comment by nmellado** [comment]
It looks like we proposed the same structure @dlyr , what difference are you suggesting ?
Just flattening the content of the Geometry folder ?

**Comment by dlyr** [comment]
Yeah I mean have only one subdir level in Core might be sufficient

**Comment by louen** [comment]
I agree that `Tasks` need to stay in `Core` as they do not depend on any engine feature.
You can use a task queue for a batch processing application which depends only on `Core`.

In addition, there is some stuff  (in fact, most stuff) in `Math` that should go in `Geometry`

**Comment by nmellado** [comment]
Regarding `Tasks`, I do agree. (btw, I've never explicitely suggested to move `Task` out of `Core`, I was just asking).

Regarding `Math`, please be more detail explicitly what should stay in `Math`, and what should move to `Geometry`.

**Comment by louen** [comment]
Probably the two should be merged, as  anything besides maybe `LinearAlgebra` is atually geometry. I would argue for a second level hierachy here though.

**Comment by nmellado** [comment]
As suggested by @dlyr , the `Core` hierarchy as only one level. See commit message 
e04b0d6: 
```
The new src/Core hierarchy is :
./Animation
./Asset
./Container
./Geometry
./Utils
./Tasks
And changing namespace to match this hierarchy

following issue #302
```

**Comment by nmellado** [comment]
Changes have been made in #403, which is about to be merged.
Closing.
