### ISSUE TITLE
Design to allow animation/simulation plugins

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#324]
I am currently working on a physics simulation plugin that I would like to couple with the animation plugin, so that both can play/pause/step/reset at the same time. I also would like to save/load the current state at some frame so that I can tweak some keyframed parameters without having to rerun the whole animation.
I already have some more-or-less dirty modifications of the Radium API with a keyframed value editor, but I would like to integrate a better, nicer design for this kind of situation.

What I have for now:
 - play/pause/step/reset methods in `Ra::Engine::System`
 - load/save methods in `Ra::Engine::Component`
 - my plugin's system is responsible for calling the load/save methods on all the mandatory components
 - Plus I had to find a way to get the app framerate

I would like to discuss with you about a nice design for this. Any idea?
Thanks

**Comment by MathiasPaulin** [comment]
Well, before giving some design intuition, somme comments on the following points : 
- play/pause/step/reset methods in ``Ra::Engine::System``
I'm not sure that having play/pause/step/reset method in ``Ra::Engine::System`` is a good idea. This interface is specific to animation systems, or, if we want to be more general, specific to time-dependent systems. 
- load/save methods in Ra::Engine::Component
I don't understand what you want. A component is created by a system and has no self load/save power. This allow to set and verify **invariant** on the components and ensure that a system will always known the state of its component without requesting them.
- The app framerate is, by definition, application specific. So, the app must communicate this to the system, and not the opposite (the system poll it from the app). This will ensure that systems and component will be application independent. Useful to develop small application demo outside of the main-app and to re-use several piece of software in plugins.

What I'll prefer is the following : 
- a subclass of System that define the time-dependent interface. Let's call it ``TimedSystem```
- All the animation systems implement this interface so that an application or plugin that manage animation system could use this interface
- A specific ``TimedSystem`` that is just in charge of coupling several ``TimedSystem`` i.e. that manage the synchro between several ``TimedSystem`` by propagating the plat/pause/step/reset calls and that could do even more ...

With this, if your application or plugin need to couple TimedSystems, you create a coupling system, you add the systems you want to couple to your coupling system and remove them from the Engine system set, you only add the coupling system to the engine. As the removed systems will no more be signaled by the engine but only by the coupling system, you can **set and ensure all the invariants** you need for your coupling. More, you will be able to **control the way your systems are coupled** (if you need to temporarily suspend the coupling, if you need to communicate with the coupled systems some hidden informations, if you need to have different time-steps on your coupled systems ...).

**Comment by hoshiryu** [comment]
Solved by #347, closing.
