### ISSUE TITLE
Can't clear scene that containts light [master-v1]

### ISSUE THREAD

**Issue by PierreMezieres** [STORM-IRIT/Radium-Engine#325]
Hello,

I'm currently working on a pbrt file loader, so I want to add lights on the scene.
I'm working with the Radium branch "master-v1" and with the last commit (f9c2297).

The only thing I do is to create a LightData, set it and push it on the fileData.
A little bit like this:
` Ra::Asset::LightData *light = new Ra::Asset::LightData("light");`
`light->setLight(color,direction);`
`fileData->m_lightData.push_back(std::unique_ptr<Ra::Asset::LightData>(light));`

Radium loads the lights correctly, but crash happens when I try to remove a light or clean the scene.
(It crashes with each light types)

If it can help, according to gdb, it crashes on the function :
`ForwardRenderer::renderInternal( const RenderData& renderData)`

**Comment by MathiasPaulin** [comment]
@PierreMezieres Thanks for the report, this is easily reproducible without plugins. It's an Engine and Application (main-app) bug. We'll fix it quickly.

**Comment by MathiasPaulin** [comment]
Fixed by PR #326
