### ISSUE TITLE
Camera fit scene 

### ISSUE THREAD

**Issue by ThibaultLejemble** [STORM-IRIT/Radium-Engine#327]
When the `TrackballCamera` is fitted to the bounding box of the scene using `TrackballCamera::fitScene(aabb)`,  the _Z_-coordinate of the camera is not correctly updated since the _Z_-coordinate of the box's center is not taken into account.

The line **225** of `TrackballCamera.cpp` which is at the moment:
```c++
m_camera->setPosition( Core::Vector3( aabb.center().x(), aabb.center().y(), d ) );
```
should be:
```c++
m_camera->setPosition( Core::Vector3( aabb.center().x(), aabb.center().y(), aabb.center().z()+d ) );
```

For instance, If an object is translated along the +_Z_-axis, the fitted camera will be positioned between the origin and the object and will be looking toward the origin, so the object will not be seen at the screen.

If a pull request is needed, should I create one for the branch `master` or `master-v1`?

**Comment by MathiasPaulin** [comment]
Fixed by PR #329
