### ISSUE TITLE
Camera reset when changing renderer

### ISSUE THREAD

**Issue by ThibaultLejemble** [STORM-IRIT/Radium-Engine#328]
When changing the current `Renderer` from the user interface, the camera is reset. But I wouldn't have expected any change of view... Is this a normal behavior?

This is due to the following method, which is called _only_ when the `Viewer` changes its `Renderer`:

```c++
    void MainWindow::onRendererReady()
    {
        m_viewer->getCameraInterface()->resetCamera();
        updateDisplayedTexture();
    }
```
I tried to comment the `resetCamera()` call and it seems that it's working fine.

**Comment by MathiasPaulin** [comment]
I agree with you,  the best behavior is to not reset the camera when changing renderer. 
add this to your PR concerning #327 on master-v1

**Comment by MathiasPaulin** [comment]
Answer is integrated by PR #329
