### ISSUE TITLE
Crash when using -f option 

### ISSUE THREAD

**Issue by ThibaultLejemble** [STORM-IRIT/Radium-Engine#339]
When loading a file from the command line using _-f_ option, the application crashes because the camera, which does not exist yet, is fitted to the scene.

The `CameraInterface` is indeed created by the `Viewer` when it is initialized by `Viewer::initializeGL()` which is called at the first `Viewer::resizeEvent()` during the first `BaseApplication::radiumFrame()`. However, with the _-f_ option, the `BaseApplication` loads the file during its construction before any frame.

I think this issue raises the more general question about the role of the camera and the fact that it should be a proper `Component`. Anyway, I quickly solved the problem by creating the camera at the same time as the OpenGL context is set (in `Viewer::showEvent`). If it's the right way to do this, I'll propose these changes in a future pr.

**Comment by nmellado** [comment]
True, this is related to the camera management.
The plan would be to have the camera attached to an entity (as suggested [here](https://github.com/STORM-IRIT/Radium-Engine/issues/314#issuecomment-388875957)).

If others agree, I suggest you add a PR with the quick fix (with comments in the code referencing this issue), while we let this issue opened until we fixed the problem.

**Comment by MathiasPaulin** [comment]
Well, after a quick look at your problem, I think that your workaround is not really the right way to solve the problem. More, the show event is deferred on some systems (e.g. MacOs). So, as said by @nmellado while I was typing this comment, clearly indicate in your PR that this is  a workaround to remove once the camera management will be refactored.
