### ISSUE TITLE
Feature request: attribute management and TopologicalMesh edition

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#342]
As described in PR #305 , per-vertex attributes (e.g. colors, texture coordinates) are kept untouched by OpenMesh algorithms and the `SplitEdge` operation provided by Radium (https://github.com/STORM-IRIT/Radium-Engine/pull/305#issuecomment-391613990).

A mechanism need to be provided to preserve attributes during topological changes, for instance: 
 - by extending the topological operations in Radium to interpolate / blend attributes
 - by extending OpenMesh algorithms.

**Comment by dlyr** [comment]
Well, after reflection, I think I could do something fine for the edge split part rather quickly ;) maybe by the end of the day.

**Comment by nmellado** [comment]
I was thinking we could take this opportunity to add missing operations, like the `CollapseEdge` for instance.
Anyway, it's good you can do the `SplitEdge` quickly.

**Comment by dlyr** [comment]
(we can still accept the PR in its current state, then refactor, then add missing operators)

**Comment by MathiasPaulin** [comment]
Closed by #350
