### ISSUE TITLE
Broken skinning

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#343]
On branch master-v1, the skinning plugin is broken: neither LBS or DQS work correctly.

**Comment by hoshiryu** [comment]
This seems to be due to the copy operator for `TriangleMeshes` and the way attributes are managed.
The `AttribManager` stores pointers to the `Attribs`, which are the one that are copied when copying the `TriangleMesh`. Hence the `TriangleMesh` and its copy share the same attribute location, and modifying one also modifies the other.

**Comment by nmellado** [comment]
True, I remember we talked about that with @dlyr.
A deep-copy method need to be added to the attributes manager. I suggest we call it clone.

**Comment by dlyr** [comment]
Right we talked about that, and I totally forgot.
Well we can also overload copy ctor, and add a move ctor ?
Btw no time to do that before next week (at least) so fell free to propose the corresponding PR.

**Comment by hoshiryu** [comment]
Yes
