### ISSUE TITLE
Attributes and topological meshes

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#348]
While implementing attributes-aware subdivision, I had some issues with the resulting attributes and normals.
I thus tried to just convert a TriangleMesh with uv-coordinates into a TopologicalMesh, then convert it back to check attributes management during conversions.
And actually, there is an issue with it as can be seen on the [following image](https://drive.google.com/open?id=1Ua7D-4pGRosKDpgPycZu4acdNRJCwleX)

**Comment by hoshiryu** [comment]
Actually this comes from the fact that no attribute except position and normal are stored in the `TriangleMesh`.
When loading the mesh and building the `FancyMeshComponent`,  all attributes (texture coordinates, tangents, colors) are directly loaded into the `Ra::Engine::Mesh`.

**Comment by dlyr** [comment]
well the Mesh data are transferred to TriangleMesh (see [here](https://github.com/STORM-IRIT/Radium-Engine/blob/23edc296e65c367089f49631f0c3d37e2e22a2d4/src/Engine/Renderer/Mesh/Mesh.cpp#L171 ) )

**Comment by dlyr** [comment]
But, we going back and forth to topoMesh, I think we need to recreate the Engine::Mesh (as a temp solution)

**Comment by hoshiryu** [comment]
ok, I should have put the code after the `Mesh::addData()` calls

**Comment by dlyr** [comment]
Right but the handles would be invalidated 

++ david
