### ISSUE TITLE
Investigate memory management of object in renderer

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#35]
Look up who owns rendering related objects such as RenderTechniques, shaders and materials. Bad memory leak is bad.

**Comment by Zouch** [comment]
This could / should / might / can be done using an Asset Manager

**Comment by hoshiryu** [comment]
Ping: is this issue still topical?

**Comment by dlyr** [comment]
I think this issue is not relevant anymore.
Feel free to reopen.
