### ISSUE TITLE
Clean Radium Options

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#390]
When Compiling Radium with non-default options, there are some small issues (not detected by the CI since it runs only with default option values):
 - `RADIUM_WITH_DOUBLE_PRECISION`: in the code, there are some real constants that are not cast into the `Scalar` type, some variables are typed `float` instead of `Scalar`, and the same goes for some function/method parameters.
 - `RADIUM_WITH_OMP`: msvc does not with OpenMP 3.0, thus forbidding the use of `unsigned int`s as for-loop parameters.

I didn't test all options and some issues might still be hiding.
All this should be addressed before the v1 release.

**Comment by nmellado** [comment]
Related: #274
