### ISSUE TITLE
[doc]Improve compilation how-to for non-expert users

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#410]
Some users fail at compiling Radium because they open the main_app cmake file instead of the main one.
This is actually not described in the compilation instruction (readme.md).

**Comment by dlyr** [comment]
I do not understand which readme.md file you are referring. Radium-Engine or Radium-Apps ?

**Comment by nmellado** [comment]
Hum, that's a very old issue, where Sandbox was still on Radium-Engine repo.
Closing.
