### ISSUE TITLE
gcc version and std::clamp

### ISSUE THREAD

**Issue by ThibaultLejemble** [STORM-IRIT/Radium-Engine#421]
In section [Supported compiler and platforms](https://github.com/STORM-IRIT/Radium-Engine#supported-compiler-and-platforms) in `README.md`, it's written that gcc 5 or higher is required for _Linux_. 
But `std::clamp` is used in several part of the code, which is a c++17 feature available only from gcc 7.1 ([gcc status](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html)).

The documentation of Radium should be updated, or a custom clamp function should be used (as before https://github.com/STORM-IRIT/Radium-Engine/pull/411).

**Comment by nmellado** [comment]
Thanks for the report.
Yes indeed we use cpp17, so we need to update the minimal version for the compilers in the documentation.

**Comment by nmellado** [comment]
Fixed by 6c8e953
