### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#426]
There is a lot of branches on STORM-IRIT/Radium-Engine.
These branches should be deleted to cleanup this repository.
Please copy your active branch on your own fork so taht STORM-IRIT repo stay clean.
I have started this work on the branch I was involved in.
In the future I think we should not create feature branch on STORM-IRIT, just have a master, with tags.

**Comment by hoshiryu** [comment]
I forked Radium so that I keep all the branches I'm involved in, except for the build chain tests (related to issue #344)

**Comment by dlyr** [comment]
To sum up, please answer by one week.
  remotes/origin/anahid_mesh_contact -> delete ?
  remotes/origin/asset_manager_clean -> delete
  remotes/origin/baptiste -> delete ?
  remotes/origin/bbw -> delete
  remotes/origin/celine_clean -> delete ?
  remotes/origin/celine_rebased -> delete ?
  remotes/origin/gh-pages -> KEEP
  remotes/origin/manage_y_scheme -> delete ?
  remotes/origin/master -> KEEP
  remotes/origin/master-v0 -> KEEP
  remotes/origin/remeshing2  -> delete ?
  remotes/origin/test_impl_dyna  -> delete ?
  remotes/origin/val_test_fit_muscle  -> delete ?

**Comment by nmellado** [comment]
Checking with @Ana873331 .

**Comment by dlyr** [comment]
Cleaned
