### ISSUE TITLE
Recording during n frames

### ISSUE THREAD

**Issue by ThibaultLejemble** [STORM-IRIT/Radium-Engine#443]
I would like Radium to open a PLY file and a camera file, to record one frame, and then to close.

I tried `./main-app -f mesh.ply -c camera.cam -n 1`, but no frame is recorded and Radium does not close.

Is there something wrong, or did I misunderstand the option `-n`?

I quickly checked `BaseApplication.cpp` and saw that 
- the option `-n`  does not set `m_recordFrames` to `true`
- when the number of rendered frames reaches the number of frame given by `-n`, the method `appNeedsToQuit()` is called but Radium continues to run

**Comment by hoshiryu** [comment]
Currently we don't have the app option to record frames, what `-n` does is just  `Run for a fixed number of frames`.
However, the app should effectively close at the end.
