### ISSUE TITLE
Make the SSE level a configurable variable in CMake

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#45]
On old machines SSE 4.2 is not always present, so it should at least be possible to pass an option to cmake to downgrade to an older SSE set. (even better if we can do it automatically...)

**Comment by nmellado** [comment]
Shall we use this ? 
https://github.com/hideo55/CMake-FindSSE/blob/master/FindSSE.cmake

**Comment by nmellado** [comment]
@louen , except if you have a good reason to push this, I suggest to close this issues, since we don't target this kind of machines.

**Comment by louen** [comment]
Yeah I changed laptop and the new one has SSE 4.2. Maybe we can just check that the machine is recent enough to support these instructions ?

**Comment by nmellado** [comment]
Yeah, why not.

Another option would be to use this: https://github.com/VcDevel/Vc:
 * https://github.com/VcDevel/Vc/blob/master/cmake/FindSSE.cmake
 * and better: https://github.com/VcDevel/Vc/blob/master/cmake/OptimizeForArchitecture.cmake.

We can also copy theses files, as long as we respect their Licence (sound good for me).

**Comment by louen** [comment]
I concur

**Comment by MathiasPaulin** [comment]
Same ... 
Nevertheless, I prefer a findSSE instead of an include ... but the argument given in the second against the first is pertinent as long as we compile on oooooooold kernels. Seems that it will be never the case. So, go for the findSSE version.

**Comment by MathiasPaulin** [comment]
Yep but this findSSE.cmake is quite old (SSE4.2 is not detected) and will require a findAVX.cmake or a Find<YOURCPUFEATUREHERE>.cmake for other vectorization API. If someone could port the OptimizeForArchitecture to a FindXXX ???

**Comment by nmellado** [comment]
Let's keep the todo flag ON, and wait for the first developer able to fix it.
