### ISSUE TITLE
Adding a listener in a listener

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#457]
Seems to be a bad idea, I miss this one during review.
https://github.com/STORM-IRIT/Radium-Engine/blob/e39e9a7440ae1f7bebcb8adea9b55e7bc23fa19d/src/GuiBase/Viewer/Viewer.cpp#L66

I'll prepare an update, but I have differents solutions in mind :
directly call camera and gizmo register method,
add an helper, that register the three callbacks,
move the callback registration in base app ... but it means any base app has to have a gizmo and a camera.

**Comment by MathiasPaulin** [comment]
Why is it a bad idea ? The viewer own the camera and the gizmos. So, it has also the ownership on keymapping configurations for both these. 
The last solution you proposed was the one removed when submitting the PR doing these registration. 
Direct call is unclear for me but if this require to expose the camera and gizmo, not a bad idea neither.
Perhaps an helper that register everything ? butviewer, camera and gizmo are tightly linked, so the current solution seems fine for me.

**Comment by dlyr** [comment]
The bad idea is that `void Gui::Viewer::registerKeyMapping()` is called each time a new configuration is loaded, so it adds  `Gui::TrackballCamera::registerKeyMapping` to the list of listener again and again, and so `Gui::TrackballCamera::registerKeyMapping` is called multiple time.
Hence `Gui::Viewer::registerKeyMapping()` do not play the callback role anymore.

So the good solution will be :
```c++ 
Viewer::setupKeyMappingCallbacks {
 keyMappingManager->addListener( Gui::TrackballCamera::registerKeyMapping );
 keyMappingManager->addListener( Gui::GizmoManager::registerKeyMapping );
 keyMappingManager->addListener( registerKeyMapping );
}```

**Comment by MathiasPaulin** [comment]
Ok, fine for me
