### ISSUE TITLE
Mesh attrib observer

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#461]
To allow seamless access to TriangleMesh thru Renderer::Mesh, with auto setDirty and update, I plan to add an Observable mechanism to Attribs.
* First possibility is to remove direct access to attrib data, so one need to copy data, modify data, and set data (so with data duplication, at least one...)
* The other possibility is to let the user call attrib->notify() when done
* The last possibility I have in mind is to lock attrib (like map buffer in opengl) with the getter, and then unlock explicitly by the user when done, which then notify the observer. 
Only one lock will be possible at a time, with some boolean that tracks lock/unlock.

Any feedback ?

**Comment by nmellado** [comment]
I like the lock version, it is very useful for deferred updates and re-entrant access.

**Comment by dlyr** [comment]
Yeah and still high performances (without copies) and with some kind of data protection mechanism

**Comment by dlyr** [comment]
solved by #454
