### ISSUE TITLE
Point clouds not displayed

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#488]
I tried to load a point cloud from a `PLY` file, but the point cloud is not displayed, while it was displayed some time ago.
The `Stats` tab from the main-app tells me the vertices are there.
There might be some compatibility issue between the new `Core::Meshes` and `Engine::Meshes`.

Also, I have an error on tinyply, which might not be related here (since I seem not able to open issues on the tinyply repo, I put this here for @nmellado ):
```
[TinyPLY] the following property keys were not found in the header: alpha, 
[TinyPLY] the following property keys were not found in the header: red, green, blue, 
```

**Comment by nmellado** [comment]
There is currently an issue with Radium renderer which does not display point-clouds..
They will be black with PR #476 , however the color of the point-cloud is not working yet. 
@dlyr had a fix in mind if I am right.
