### ISSUE TITLE
Dependency between GuiBase and IO

### ISSUE THREAD

**Issue by ThibaultLejemble** [STORM-IRIT/Radium-Engine#491]
The doc [here](https://storm-irit.github.io/Radium-Engine/develbuildchain.html) says that _GuiBase_ depends only on _Core_, _Engine_ and _PluginBase_ :
```
add_dependencies (${ra_guibase_target} PUBLIC Radium::Core Radium::Engine Radium::PluginBase )
```
But the CMakeLists.txt also adds _IO_ :
https://github.com/STORM-IRIT/Radium-Engine/blob/c5b1517b49d1bbe914865491757d212c39de8c45/src/GuiBase/CMakeLists.txt#L32
The doc needs to be updated or the dependency to _IO_ should be removed.

**Comment by MathiasPaulin** [comment]
Well, IO was added on the CMakeLists.txt only because BaseApplication (that is the main part of main-app) requires it.  
BaseApplication could be removed from GuiBase as it represent fully the main-app and not a reusable software component. 
It only define the main-app behavior and is not needed (nor usable) by applications that build over Radium that just need the Viewer class.
This must be analyzed more deeply, as some functionalities (e.g. loading plugins), are demonstrated in BaseApplication.
The easier for now is to update the doc. Removing BaseApplication will be done in the near future.

**Comment by dlyr** [comment]
In current state, you can easily extend the mainapp by deriving from BaseApplication. This behvior looks right to me.
But we can state that IO is related to the actual application and remove the dependance between BaseApplicaiton and IO (i.e remove the call to registerFileLoader in BaseApplication, and let any MainApplication do the work).

**Comment by MathiasPaulin** [comment]
I'm not sure it will be straightforward nor that the BaseApplication is ready for extension. Do you have an example ? I will test. 
But in this case, what about several app options related to file loading (e.g. fileOpt and camOpt). This could also be transferred to the derived app but then, how to prevent collisions on the BaseApplication `QCommandLineParser` and the one eventually proposed by the derived app.
And what about the comment (line 150 of BaseApplication.cpp) stating that 
```// Public variables, accessible through the mainApp singleton.```
And what about loading of plugins. By default, BaseApplication load all plugins from the "Standard Plugin path". If we dont want, for an application, such "Standard plugins"

**Comment by dlyr** [comment]
Actually I already did it for a private project (derive from BaseApplication and add functionality or change behavior), but it's not updated to last master, so some functionality might have changed.
I'm not sure about the file loading stuff, I think we can keep it in BaseApplication and update the doc about dependecies.
The BaseApplication need to be cleaned up to move any *specific* things to MainApp (out of radium lib), 
If you talk about BaseApplication.hpp, these variables are accessible trough qApp, casted to your application class (see [here](https://github.com/STORM-IRIT/Radium-Apps/blob/00464e3003b83191b40f1479c39e076d5f824eac/MainApplication/MainApplication.hpp#L4))
The plugin related stuff need to be fixed, the old behavior depended on working directory, which was fine for my usage. I will try to update my private project to check how it works with the uptodate master.

**Comment by MathiasPaulin** [comment]
Well, I've tested (with the branch toward-v2 and my rendering app from my private gitlab repo - branch `withBaseApp` - you might access it).
It (almost) work.
- As you mentioned, a lot of main-app specific things must be moved outside BaseApplication (logging, file loading ... )
- Extending the command line options, to add some application specific options doesn't work. The only thing we can do is to construct a second QCommandLineParser with specific options and process it. But this is not working (kill the app with a Qt error message ... need to investigate)
- Some signals are intercepted before you can connect them to something useful in your application (e.g `Ra::Gui::Viewer::glInitialized` that is intercepted by the `processEvents()` called in the constructor of BaseApplication.cpp). So, the only thing you can do is to expect that OpenGL is initialized when you're in the derived constructor (seems sage nevertheless but ...)
- Plugins are loaded by default and you don't have an option to load only some (or none) of them as you call the base constructor before executing anything else in your derived constructor.
- The plugins locations are fine. The default location is in the Radium install directory and you can add your own locations through a call to `addPluginDirectory(...)`
- the "singleton like" qApp, casted in the main app is not a really god idea if you want to access this from another part (or lib) of your application. This add dependance on an application specific file. But we can do without this "singleton like horror" ;)

**Comment by dlyr** [comment]
To conclude : update the doc to add a dependency between IO and GuiBase.

**Comment by MathiasPaulin** [comment]
and refactor a little bit Base application to remove this dependency afterward while allowing applications to derive from BaseApplication fluently.

**Comment by dlyr** [comment]
It's not linked to this issue. Please open another issue related to base application

**Comment by MathiasPaulin** [comment]
its linked to this issue. The doc is OK, there is no need of dependency between GuiBase and IO. This is just due to a forgotten aspect of guibase when developping the new buildchain.
