### ISSUE TITLE
Missing functionality : texture coordinates transformation and texture coordinate layers

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#518]
When using Radium with general assets coming from content creation software, I remark that several models (quite a big number of them) use texture coordinates in a way that is not available in Radium. 
The two following functionalities are missing and will be valuable if added to the Radium Engine : 
  - Texture coordinate transform : this is an IMPORTANT requirement for our use-cases. This concern the capability to associate a different transformation matrix for different textures. This will allow, e.g., using a single texture coordinates layer, to apply textures defined at different scales/orientation. As textCoord are vec3 in Radium, this transformation could be a 3x3 transformation matrix associated with each texture. Ihave an idea on how to make this, I'll try to propose a draft of solution in the next days.
  - Texture coordinate layers : capability to define at least 2 layers (as in, e.g. the GLTF specification) of texture coordinates for each object. This is less crucial as the functionality could be implemented using specific shaders/ parameterproviders and the capability we have to add user defined vertex attribs on the geometry. But a general interface allowing to (re)use existing shaders could be helpful.

**Comment by dlyr** [comment]
Hi,
For the second point it is already supported with current implem of attrib, you just have to follow your naming convention. I'm not sure I see all the use cases, but if one need to specify the mapping between texture, texture coordinate, and texture usage (e.g. use texture as normals or texture as roughness), it may be interesting to have an uber shader mechanism. So the resulting shader is optimize to the material properties of the object.

For the first point. A quick fix should be to bake texture transformation when exporting the file from the creation software. It will not work if you want to animate the transformation texture.
The the question is, do the matrix is part of the texture, or of the association between a material and a texture, or of the association between the object and the texture, thru a material ?

**Comment by MathiasPaulin** [comment]
> Hi,
> For the second point it is already supported with current implem of attrib, you just have to follow your naming convention. I'm not sure I see all the use cases, but if one need to specify the mapping between texture, texture coordinate, and texture usage (e.g. use texture as normals or texture as roughness), it may be interesting to have an uber shader mechanism. So the resulting shader is optimize to the material properties of the object.

I agree with this and defining the Uber shader you mention is what I call Shader Compositing ...

> For the first point. A quick fix should be to bake texture transformation when exporting the file from the creation software. It will not work if you want to animate the transformation texture.
> The the question is, do the matrix is part of the texture, or of the association between a material and a texture, or of the association between the object and the texture, thru a material ?

Baking transformation is not the solution because you can access several textures for the same material from the same texcoord (normal, diffuse, specular, roughness ....). So, this is not a solution (i tried it ;) )
If we consider that a texture is defined by several properties : images, sampler and semantic that corresponds to the content, the way we access to the content and the usage we do of the result. I think that we could associate the transformation to the sampler. The image could be used through several sampler, the semantic (defined by the material) is agnostic on the way the information is computed ...

**Comment by MathiasPaulin** [comment]
I propose a non intrusive solution for this missing feature (PR #521). 
Shader parameter provider, that are aware of internal state of shader/material/other resources might add some properties to the shader so that, when compiled, it is able to manage texture transform. Shader Properties, in Radium, correspond to a list of symbol to define in the shader source code. Properties are added as `#define PROPS` in the shader source before its compilation.
The proposed solution (PR #521 that depends on PR #520) is not limited to texture coordinate transform and will be discussed to study its extension to other shader configuration elements (include, code snippet, ...).
