### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#525]
Adding a doc about plugin raise the question of documentation structure, from #524 discussion
The current doc tree seems broken (may be due to the update of doxygen configuration, but the fix will be added to #524

So the current expected tree is 

-  Radium Engine
	- Radium Basics
		- Badges
		- Table of content
		- Compilation instructions
		- Use Radium Libraries in your own project
		- Troubleshooting
	- Radium Concepts
		- Concepts: Forward Render
	- Developer manual
		- How to code in Radium
		- Coding conventions for Radium
		- Radium Engine programmer manual [old version]
		- Radium Build Chain
		- API: 3D objects (a.k.a. Meshes)
		- API: Rendering pipeline
		- API: Material management
		- API: Lights
		- API: Feature Picking
		- API: KeyMapping
		- API: Camera manipulation in Radium
		- API: Animation pipeline
		
The question is where should we add doc about plugins and application dev (which I think are part of Radium-Engine repository, not Radium-Apps nor Radium-ExamplePlugins)

I propose to rename Developer manuel to Lib dev manual, and add a App/plugin dev manual

**Comment by nmellado** [comment]
Remember that there is the repository Radium-releases (still not ready, siding had time to work on it), which could hold the documentation of the whole ecosystem.

**Comment by dlyr** [comment]
Right, the user manual of the main-app (i.e. where to click) could be there.
But the explanation on plugin dev and app dev are more related to the lib, and I think they should be included in this doc.

**Comment by MathiasPaulin** [comment]
I agree with @dlyr, documentation on plugin and app dev should be included in the dev manual section of the documentation. 
But I'm dubious about how to organize this doc. There are parts that are common to Lib dev and to plugin/app dev, such as `How to code in Radium` or `Coding conventions for Radium` ... and developing plugins or app need a quick access to the API documentation.
So, why not a structure like the following ?
- Radium Basics
    - badges & ... & Troubleshooting
    - Radium ecosystem : apps and plugins
- Radium Concepts
    - Geometry : mesh & points
    - Rendering : forward renderer
    - Animation : ...
- Developper Manual
    - How to code in Radium
    - Coding convention
    - Radium build chain
    - Radium API
        - Radium Core
        - Radium Engine
        - Radium IO
    - Plugin dev
        - Plugin build chain
        - Plugin API
    - Apps dev
        - Apps build chain
        - GuiBase API
        - Command line API

**Comment by dlyr** [comment]
By the way, badges were ill placed. It seems that the main pages titles are added to the first page ... so I remove the titles form the main page, I do not find another solution
Also pages should not have both a h1 title and a \page token, so I remove h1 titles in the PR

**Comment by dlyr** [comment]
Done in the PR, I still have some issue with some section ill placed in the treeview, but the pages are ok (and the related page view form the top nav is ok).

Here is an overview (still need polishing)
 
-  Radium Basics	
   -   Compilation instructions	
   -   Use Radium Libraries in your own project	
   -   Troubleshooting	
-  Radium Concepts	
   -   Concepts: Forward Render	
-  Developer manual	
   -   How to code in Radium	
   -   Coding conventions for Radium	
   -   Radium Build Chain	
   -  API	
	  -  Core	
		  -   API: 3D objects (a.k.a. Meshes)	
	  -  engine	
		  -   API: Rendering pipeline	
		  -   API: Material management	
		  -   API: Lights	
		  -   API: Feature Picking	
		  -   API: Animation pipeline	
	  -  Gui	
		  -   API: KeyMapping	
		  -   API: Camera manipulation in Radium	
	  -  Plugin dev	
		  -   How to write your own plugin	
	  -   Application dev	
	  -   [deprecated old version]Radium Engine programmer manual	
-   Licenses	
-   Todo List	
-   Deprecated List

**Comment by dlyr** [comment]
issue open on [doxygen side](https://github.com/doxygen/doxygen/issues/7704#issue-600884644)

As an answer to @MathiasPaulin , what kind of doxygen warning do you have ?
The purpose of #524 is to setup the doc structure, with some improvements (taken from the PluginExample repo), but not to rewrite everything.
Fixing doxygen warnings is also an options, depending on the kind of options and how long it takes.

**Comment by MathiasPaulin** [comment]
I agree, PR #524 is to setup doc structure. But, doxygen warning, related to doc structure or doc formating might be solved also. I can do that but need to know where.
Here are some warning messages i got when building documentation.
```warning: failed to open layout file '/Users/mathias/Professionnel/SVN-IRIT-paulin/paulin/Developpement/Radium/Radium-Engine/doc/doc-src/layout.xml' for reading!```
```warning: source /Users/mathias/Professionnel/SVN-IRIT-paulin/paulin/Developpement/Radium/Radium-Engine/doc/examples is not a readable file or directory... skipping.```
```warning: source /Users/mathias/Professionnel/SVN-IRIT-paulin/paulin/Developpement/Radium/Radium-Engine/cmake-build-release/doc/doc-src is not a readable file or directory... skipping.```
```warning: source /Users/mathias/Professionnel/SVN-IRIT-paulin/paulin/Developpement/Radium/Radium-Engine/doc/doc-src/images is not a readable file or directory... skipping.```

**Comment by dlyr** [comment]
Done on the doxygen configuration side.
For the other warnings, there are related to the sources, I think some are related to doxygen limitations, need further investigation.

**Comment by dlyr** [comment]
Configuration and files have be set for doxygen 1.8.13, the version currently used by continuous integration and automatic documentation deployment.
