### ISSUE TITLE
Submodule fetch tag (Assimp)

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#526]
I just went across an issue with Assimp when configuring Radium with
```
cmake ../Radium-Engine/ -DCMAKE_BUILD_TYPE=Release -DRADIUM_IO_ASSIMP=ON -DRADIUM_SKIP_IO_EXTERNAL=OFF
```
I get the following issue that was not there before:
```
[100%] Built target assimp
-- [addExternalFolder] Build ended
-- [addExternalFolder] Configure package file /home/hoshiryu/dev/Radium/build_radium_release/src/IO/external/cmake/package-IO.cmake
CMake Error at Bundle-GNU/lib/cmake/assimp-5.0/assimpTargets.cmake:71 (message):
  The imported target "assimp::assimp" references the file     "/lib/libassimp.so.5"  but this file does not exist.  Possible reasons include:  * The file was deleted, renamed, or moved to another location.  * An install or uninstall procedure did not complete successfully.  * The installation package was faulty and contained     "/home/hoshiryu/dev/Radium/Radium-Engine/Bundle-GNU/lib/cmake/assimp-5.0/assimpTargets.cmake"  but not all the files it references.Call Stack (most recent call first):
  Bundle-GNU/lib/cmake/assimp-5.0/assimp-config.cmake:1 (include)
  src/IO/CMakeLists.txt:25 (find_package)
``` 
It actually seems to come from new commits to the AssImp repository's master branch.
When I change the AssImp fetched branch from `origin/master` to `origin/assimp_5.0_release` in file `src/IO/external/CMakeList.txt` all goes right.

**Comment by nmellado** [comment]
I couldn't replicate this behavior.
Could you detail your configuration (OS, compiler, cmake version, etc) ?

**Comment by dlyr** [comment]
I had the same issue, but I think it's fixed on assimp side.
Look like they have some issue on their side see their commits on april 16th
Anyway specifying a fixed tag or commit is a good idea. 
If we don't need last master, we can use the last tag i.e  GIT_TAG v5.0.1 
I see that Tinyply also points to origin/master, might be a good idea to use commit id or tag if they provide one.

**Comment by nmellado** [comment]
Agree.
We can have a dedicated PR for that. If we do it, we can also update the Eigen repository which moved to gitlab.
