### ISSUE TITLE
Commit 1356bdac71d2ebb7992809d1c94404e5d5998469 breaks MacOs compilation in Debug mode

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#546]
Due to wrong assimp library naming on MacOs, the PR #540 breaks macos compilaiton in debug mode. this is fixed by the commit 379d59bcbd831ad07fcafcf5515bc7b0fee8640f on assimp's github.

**Comment by hoshiryu** [comment]
On the other hand, commit `379d59bcbd831ad07fcafcf5515bc7b0fee8640f` breaks skeleton animations: there seems to be issues in rotations (will need further investigation to determine if its due to assimp or the way we load data)

**Comment by MathiasPaulin** [comment]
There are no issues (nor fixes) on skeleton or animation after this commit on the assimp side. But the MacOs Dynamic Library naming problem is fixed by the referenced commit. If you find a more recent commit that satisfy your need, (or if you fix the rotation problem in the way you load animation data) post the solution as soon as possible.

**Comment by MathiasPaulin** [comment]
solved by using the right assimp tag
