### ISSUE TITLE
RGB textures without alpha channel are not displayed correctly

### ISSUE THREAD

**Issue by ThibaultLejemble** [STORM-IRIT/Radium-Engine#549]
If an RGB image without alpha channel is used as a texture, the result is distorted and mostly in gray scale.

The images below show the same simple quad using the same texture image (png), one in RGB and the other in RGBA.    

Radium should be able to load and display RGB texture? 

RGB:
![rgb](https://user-images.githubusercontent.com/24590089/80566186-aca7f200-89f2-11ea-83c7-891fbe31422f.png)

RGBA:
![rgba](https://user-images.githubusercontent.com/24590089/80566196-b2053c80-89f2-11ea-9016-0296b75df5f2.png)

**Comment by MathiasPaulin** [comment]
Radium is able to load such texture. 
Can you ell us more on your use case (how do you configure the objects/texture ...). Do you use only Radium operations or do you have developed your own scene construction ?

**Comment by nmellado** [comment]
Could you also post here the two textures and the mesh, so we can try to reproduce this ?

**Comment by MathiasPaulin** [comment]
I got the scene from @ThibaultLejemble . I will investigate. This behavior was never observe before and I've to find where is the regression. On the Radium side or on the Assimp side ?

**Comment by ThibaultLejemble** [comment]
Maybe it comes from the image itself (or how stb load it) because I tried with another RGB image and it worked! 
Unfortunately I cannot remember how I produced the image. It probably comes from Inkscape, Gimp or the `convert` command of ImageMagick.

**Comment by MathiasPaulin** [comment]
When converting you image to jpeg with imageMagik convert, and loading the jpeg texture, the same results appears ... very strange indeed.

**Comment by MathiasPaulin** [comment]
This image (the one that is problematic above) is encoded in a way that I can't infer (nor stb at loading). Its actual size is 2090x2090, with RGB pixels. When resizing the image to any multiple of 4 (from 4 to 512 to 2088 or 2092 or ...) it is correctly loaded. For any size that is not a multiple of 4, there is the same issue than observed by @ThibaultLejemble.
![rgb](https://user-images.githubusercontent.com/11328578/80591410-f0fcb780-8a1d-11ea-8913-c778c6d7d0ff.png)

**Comment by ThibaultLejemble** [comment]
This issue appears whenever I remove the alpha channel of an image using ImageMagick: `convert texture.png -alpha off texture.png`

**Comment by dlyr** [comment]
Did you find what happens here ?

**Comment by MathiasPaulin** [comment]
No idea. I suspect imagemagik to use png properties that stb could not use the right way.

**Comment by ThibaultLejemble** [comment]
This issue happens in both release and debug mode when the image has **no alpha channel** _and_ its **size is not a power of 2**.

This archive [data.zip](https://github.com/STORM-IRIT/Radium-Engine/files/4710267/data.zip) contains quads with different textures of size 256x256 and 257x257, with and without alpha channel. The file who fail is `quad_noalpha_257.obj`.

I checked the content of the image at the end of `Engine::Texture::initializeGL()` ([here](https://github.com/STORM-IRIT/Radium-Engine/blob/1356bdac71d2ebb7992809d1c94404e5d5998469/src/Engine/Renderer/Texture/Texture.cpp#L67)) and it is valid. So the `stb` library loads correctly the image.

Otherwise I have no idea if this bug comes from Radium itself, globjects or elsewhere.

**Comment by ThibaultLejemble** [comment]
In the archive above I didn't use ImageMagick but only Gimp.
I saved the images in `8bpc RGB` and `8bpc RGBA` mode, which gives :
`8-bit/color RGB, non-interlaced` and `8-bit/color RGBA, non-interlaced` when using the `file` command.

**Comment by ThibaultLejemble** [comment]
Also the issue is the same when using jpg images.

**Comment by MathiasPaulin** [comment]
> This issue happens in both release and debug mode when the image has **no alpha channel** _and_ its **size is not a power of 2**.

This is false.
The scene here display correctly and 26£à is not a power of 2. But it is a multiple of 4.
[size260.zip](https://github.com/STORM-IRIT/Radium-Engine/files/4710497/size260.zip)

Nevertheless, the problems occur on some textures ... and the resulting images looks like an alignment problems.  But the title of the issue must be changed as it is not really related to alpha channel  support on Radium...

**Comment by dlyr** [comment]
@MathiasPaulin do you mean you could not reproduce the issue of @ThibaultLejemble from his files ?

**Comment by ThibaultLejemble** [comment]
Indeed, images of size 260x260 are working, so if I correct what I said :

This issue happens in both release and debug mode when the image **has no alpha channel** and its **size is not a multiple of 4**.

**Comment by ThibaultLejemble** [comment]
@dlyr did you try to reproduce the error by loading this for instance ?

**quad_noalpha_258_jpg.obj**
```
mtllib quad_noalpha_258_jpg.mtl
usemtl default_material
v -1 0 -1
v 1 0 -1
v -1 0 1
v 1 0 1
vt 0 0
vt 1 0
vt 0 1
vt 1 1
vn 0 1 0
vn 0 1 0
vn 0 1 0
vn 0 1 0
f 1/1/1 2/2/2 4/4/4
f 1/1/1 4/4/4 3/3/3
```

**quad_noalpha_258_jpg.mtl**
```
newmtl default_material
Ka 1.000 1.000 1.000
Kd 1.000 1.000 1.000
Ks 0.000 0.000 0.000
d 1.0
illum 2
map_Kd tex_noalpha_258.jpg
```

**tex_noalpha_258**
![tex_noalpha_258](https://user-images.githubusercontent.com/24590089/83397141-6680ec80-a3fd-11ea-9bfa-9e3f5eaf7362.jpg)

**Comment by MathiasPaulin** [comment]
I can reproduce the errors on any texture that have a size that is not a multiple of 4.
I think I've found why. I'll experiment and validate the fix as soon as possible.

**Comment by dlyr** [comment]
glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
solve the issue, but maybe it's better to realign data on the cpu side.
