### ISSUE TITLE
Invalid state of default CoreGeometry in Engine::Mesh

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#572]
Currently, it seems mandatory to call the method `loadGeometry` to initialize the geometry of an `Engine::Mesh`. 
However, by default the `Engine::Mesh` contains an empty object that can be edited directly. Problem: when doing this, the communication between `Core` and `Engine` seems to be broken (GL is not updated when updating the geometry).

Here is an example in two parts, where I have a method `init_geometry` that is called once.
First, the version that works:
```c++
void init_geometry() {
    Ra::Core::Geometry::TriangleMesh mesh;

    mesh.addAttrib( Ra::Engine::Mesh::getAttribName( Ra::Engine::Mesh::VERTEX_POSITION ), someVector3Array );
    mesh.m_indices= /* something */;

    m_engineMesh->loadGeometry( std::move( mesh ) );
}
```

And here is the version that doesn't work, ie. gl is not updated:
```c++
void init_geometry() {
    Ra::Core::Geometry::TriangleMesh & mesh = m_engineMesh->getCoreGeometry();

    mesh.addAttrib( Ra::Engine::Mesh::getAttribName( Ra::Engine::Mesh::VERTEX_POSITION ), someVector3Array );
    mesh.m_indices= /* something */;
    m_engineMesh->setIndicesDirty();
}
```

I would prefer the second option as it more compact and does not require `move`.
Also in term of semantics, it means that, currently, the `Engine::Mesh` is not completely initialized until `loadGeometry` is called.

**Comment by dlyr** [comment]
I think the second example shoud be `m_engineMesh->setIndicesDirty()` and is expected to work.
Also the CoreGeometryDisplayable must be construct with a valide geometry reference.
I think we have to hide inherited ctor.

**Comment by nmellado** [comment]
Sorry I fixed a typo in my example, setting the indices as dirty does not fix the thing.
