### ISSUE TITLE
Configuring Plugins with lib

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#590]
I cannot find the documentation about how to configure a Radium-based library/plugin combo, maybe I missed it.
Nevertheless I had to go look to the corresponding PR to look for an example.
Maybe adding such an example to the `Radium-PluginExample` repo might help

**Comment by MathiasPaulin** [comment]
You have a fully functional exemple in the directory `Radium-Engine/tests/ExamplePluginWithLib/` that define a lib and its associate plugin, while the lib is used in another plugin.
The full developper documentation is still under writing.

**Comment by hoshiryu** [comment]
Please don't close until the documentation is available

**Comment by hoshiryu** [comment]
Now, I have an issue with the library configuration:
I have 2 libs, one depending on the other, and 1 plugin using both.
Would it be possible to add some `HELPER_LIBS` parameter to the `configure_radium_library` macro? or is this not the way to do that?
Also, for my plugin based on both, should I only specify the second library or both?

**Comment by MathiasPaulin** [comment]
> Please don't close until the documentation is available

I explained you, in real life, this afternoon. So, you have all you need and the doc is being written.

Quick answer to your question here  : you have to supply both !

Say, I have a lib ALib, with resources, configured using : 
```
# ... all the cmake configuration step for the target Alib
configure_radium_library(
        TARGET Alib
        TARGET_DIR Alib
        NAMESPACE Alib
        PACKAGE_DIR ${CMAKE_INSTALL_PREFIX}/lib/cmake
        PACKAGE_CONFIG ${CMAKE_CURRENT_SOURCE_DIR}/Config.cmake.in
        FILES "${public_headers};${public_inlines}"
)

installTargetResources(
        TARGET Alib
        PREFIX Alib
        DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Resources/AlibResources
        BUILD_LOCATION ${CMAKE_CURRENT_BINARY_DIR}/Resources/Alib
)
``` 
And a library BLib, that depends on ALib that you configure the same way but with  a `find_package (ALib REQUIRED)` to find its dependency, link its target to ALib and `configure_radium_library` as above.

For your plugin, you can do the following : 
```
# ... all the cmake configuration step for the target MyPlugin
configure_radium_plugin(
    NAME MyPlugin
    HELPER_LIBS ALib::ALib BLib::BLib
)
```
If you want to have ALib and BLib defined in the same package (and compiled in the same buildtree without installing the first to build the second) we have this for private projects. I'll make a PR in the next few days but for now, follow the example above and do as you always do with system libraries.
