### ISSUE TITLE
Timeline help splash screen is unreadable

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#596]
Due to strange behavior of the timeline (loop/start/stop with erroneous state and display), I hit the `?`button to have some help on how to interact with the timeline as said in the documentation.
But, here is what Is see ...
I use Qt 5.12.3, on MacOs 10.14.6.
The splash seems to set color explicitely instead of using themed colors and writing with white foreground on a white background is not really a good idea.
![Capture d’écran 2020-07-22 à 19 45 43](https://user-images.githubusercontent.com/11328578/88210126-fac83c80-cc53-11ea-8b2f-a81744d1387e.png)

**Comment by hoshiryu** [comment]
Well, I don't know what to say, it's just QLabels with text, no special color treatment

**Comment by MathiasPaulin** [comment]
> Well, I don't know what to say, it's just QLabels with text, no special color treatment

The background of the parent widget was explicitly set to white in the .ui file. 
The splash screen inherits the palette of its parent. So the background was white. So the help screen was unreadable.
Fixed (without changing anything else in the code nor in the appearance of the timeline) in PR #597
