### ISSUE TITLE
Long paths limit on windows

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#598]
For historical reasons, Microsoft Windows does not fully support path with more than 260 characters.
When compiling Radium, we often hit that limit for the dependencies, for instance:
> `build_dir/src/Core/external/Eigen3-prefix/src/Eigen3-build/doc/examples/CMakeFiles/Tutorial_ReductionsVisitorsBroadcasting_broadcast_simple_rowwise.dir/./Tutorial_ReductionsVisitorsBroadcasting_broadcast_simple_rowwise.cpp.obj`

Even if this only generates a warning, compilation often fail few steps. When looking online there are options that can be passed to the compiler to support long paths, but on my side I could not make them work (https://gitlab.kitware.com/cmake/cmake/-/issues/19675).

These long paths are caused by the way cmake stacks build directories according to the source tree. 
For convenience, we could imagine moving the external folders to the root of the repository:
~~~
| - src
  | - Core
  | - Engine
| - external
  | - Core
  | - Engine
~~~

This is clearly not critical, but could help newcomers compiling on windows.

**Comment by dlyr** [comment]
Changing from
`/src/Core/external`
to 
`/external/Core`
should reduce by 4 chars right ? is that sufficient ?
Any case, the user have to use a short prefix directory to build ...

**Comment by nmellado** [comment]
I agree that 4 characters is not a lot, but it happened to me many times that I hit the limit for 2 or 3 characters, thus this change..
Also I like the fact that all the externals are located in the same subdirectory, it looks more natural this way, with `external` and `src` having the same structure.

**Comment by MathiasPaulin** [comment]
If that works for you, go ahead and do a PR, remembering to add in the documentation the possible issue (and its solution) that some users might be experiencing.

**Comment by dlyr** [comment]
I think it's more related to the way external are compiled (and working directory setup in addExternalFolder) than source structure.
I make a test to change both, added in PR #554 (soon)
