### ISSUE TITLE
[CI] Cache dependencies source and build folders

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#645]
CI fetch and recompile Radium dependencies at each runs.
As we now have a way to manage dependencies out of Radium, it could save a lot of time to cache the source and build directories of out-of-build dependencies. This would allow to:
 - save time by skipping compilation at each run
 - still allow dependencies updates by always calling the dependencies cmake project on the cached directories (should compile only in case of change).

**Comment by dlyr** [comment]
Any hints on how to cache them ?
We could save an artifact, down/extract it, but then there is no update at all.

**Comment by nmellado** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows

It seems that we define our own keys to retrieve the cache, so we could have 4 keys: release Mac/linux/windows, debug linux (for coverage)
