### ISSUE TITLE
there is a bug in doc badge 

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#652]
codecov.io badge is not shown correctly 
https://storm-irit.github.io/Radium-Engine/
This is due to a doxygen [bug]( https://github.com/doxygen/doxygen/issues/7672) in 1.8.17, fixed in 1.8.18, but 1.8.17 is the version shipped with ubuntu-20.04, and we will stick with it for some time.
Solution 1: remove codecov.io badge :(
Solution 2: hack ubuntu to update doxygen, well, just wait
Solution 3: use a [github action](https://github.com/mattnotmitt/doxygen-action) with an uptodate doxygen
Solution 4: deploy doc manually, with an uptodate doxygen install, but no automation (well cron will automate, but no push on master trigger).

[![](https://api.gh-polls.com/poll/01EVSKMTR6J94CKD5728ADZ63J/Solution%201%20remove)](https://api.gh-polls.com/poll/01EVSKMTR6J94CKD5728ADZ63J/Solution%201%20remove/vote)
[![](https://api.gh-polls.com/poll/01EVSKMTR6J94CKD5728ADZ63J/Solution%202%20wait)](https://api.gh-polls.com/poll/01EVSKMTR6J94CKD5728ADZ63J/Solution%202%20wait/vote)
[![](https://api.gh-polls.com/poll/01EVSKMTR6J94CKD5728ADZ63J/Solution%203%20action)](https://api.gh-polls.com/poll/01EVSKMTR6J94CKD5728ADZ63J/Solution%203%20action/vote)
[![](https://api.gh-polls.com/poll/01EVSKMTR6J94CKD5728ADZ63J/Solution%204%20cron)](https://api.gh-polls.com/poll/01EVSKMTR6J94CKD5728ADZ63J/Solution%204%20cron/vote)

**Comment by dlyr** [comment]
codecov.io badge is not shown correctly
https://storm-irit.github.io/Radium-Engine/
This is due to a doxygen bug in 1.8.17, fixed in 1.8.18, but 1.8.17 is the version shipped with ubuntu-20.04, and we will stick with it for some time.
Solution 1: remove codecov.io badge :(
Solution 2: hack ubuntu to update doxygen, well, just wait
Solution 3: use a github action with an uptodate doxygen
Solution 4: deploy doc manually, with an uptodate doxygen install, but no automation (well cron will automate, but no push on master trigger).

/polls "Solution 1 remove" "Solution 2 wait" "Solution 3 action" "Solution 4 cron"

**Comment by dlyr** [comment]
Click to vote for the poll

**Comment by dlyr** [comment]
no strong champion arise.
@nmellado do you have a preference ?

**Comment by nmellado** [comment]
I think Opt 3 is the option I would favorite

**Comment by dlyr** [comment]
do not seems to work (looks like the action could not access the checkout files ... while it access the doxyfile ...)
wait is easier.
