### ISSUE TITLE
Ra::Gui vs Ra::GuiBase

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#654]
the `src/GuiBase` (and GuiBase lib) define two namespaces `Ra::Gui` and `Ra::GuiBase`.
I think only one should be used, I think `Gui` is a legacy of when we take some classes from application examples to GuiBase.
But no application should define something in `Ra:: namespace` right ? so maybe using `Gui` is more appropriate.
Here is the current state.
![Screenshot from 2021-01-18 09-26-13](https://user-images.githubusercontent.com/11328509/104890011-43488480-596f-11eb-8328-80e313fbbdb8.png)

These namespace change could be added to #642

**Comment by nmellado** [comment]
I totally agree with the fact that we need to keep only one namespace.
If we move to `Gui`, then we also need to rename the lib name from GuiBase to Gui for consistency.
I am fine to incorporate these changes in #642.
