### ISSUE TITLE
Unable to share Texture Manager betweeen renderers

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#658]
The texture manager is in charge of handling Texture resources so that a same texture is loaded only once when used the first-time and bound to an OpenGL object at the right time.

The texture manager is a singleton.
The issue comes from the creation of this singleton that is done in the `Renderer::initialize()` method. 
The singleton creation function delete any existing instance of the singleton and allocate a new instance (cf Singleton.hpp, line 26)
If several renderers are initialized, each of them delete the existing Texture Manager and replace it by a new one.
The issue is related to accessing a texture that was added to the texture manager before another renderer is created. In this case, the texture is deleted and can't be used by the new renderer.
If the texture comes from a file whose name is still valid when the texture is fetched, it will be loaded again. But if the texture was created from an image created on the fly, and not stored in a file, this texture will be no more usable.

**Comment by dlyr** [comment]
So the solution is to move the texture manager createInstance at the RadiumEngine level, right ?
