### ISSUE TITLE
Use of filesystem::lexically_normal not available in experimental

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#664]
Current version of `master` requires cxx_17 capabilities at this line: 
https://github.com/STORM-IRIT/Radium-Engine/blob/31523ca27aaa231751b9dff4e2c4343225ee2c00/src/Core/Resources/Resources.cpp#L31

Doc: https://en.cppreference.com/w/cpp/filesystem/path/lexically_normal

As such, some compilers (e.g., gcc-7) cannot compile radium.

**Comment by dlyr** [comment]
Well, filesystem is c++17, so...

**Comment by dlyr** [comment]
maybe switch to https://en.cppreference.com/w/cpp/experimental/fs/canonical
since it's both in std and experimental ? (and lexically_normal seems to be only in std c++17...)
If you can check, I'm fine with it.

**Comment by nmellado** [comment]
No I cannot check, I don't have this compiler on my computer.

**Comment by nmellado** [comment]
Ok, `lexically_normal` is not in experimental indeed (https://en.cppreference.com/w/cpp/header/experimental/filesystem).

**Comment by MathiasPaulin** [comment]
gcc-7 does not support all of filesystem. Radium needs gcc-8 to compile.
see https://storm-irit.github.io/Radium-Engine/basicsCompileRadium.html

**Comment by nmellado** [comment]
If we need gcc8 then we have to make cmake erroring for older versions.

**Comment by nmellado** [comment]
I am fine with this, we just need to pick a solution.

**Comment by MathiasPaulin** [comment]
Ok, I have a solution. But still need to ensure that every Radium based project (plugin, libs and apps) will have access to this without modifying all their cmake scripts. I'm testing ... A PR will come
