### ISSUE TITLE
Engine initialization workflow

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#670]
### Feature request : Engine initialization workflow
Allows to initialize the engine using only few function calls  so that the 
engine initialization procedure could then be the following.

1. creates the Engine singleton
This should create and initialize all the scene management services (managers).

2. initialize a set of basic systems able to work without openGL
This will register a set of system to populate the scene.
The following systems should be considered :
    - GeometrySystem (currently explicitly added by the application)
    - SkeletonAnimationSystem (soon available in the Engine, now existing as a 
      plugin)

3. initialize the OpenGL part of the Engine
This function, callable only when OpenGL is initialized, will register several 
shader programs, shader includes, base materials, base textures, ... 
It will call the openGL initialization method of the already registered systems 
(to activate some functionalities that needs openGL) and might also register 
new openGL-only system.   

By defining the Engine initialization workflow with this few function calls will
allow to
  - build OpenGL based applications by calling steps 1, 2 and 3 above from the 
application.
  - build no-OpenGL application that need basic Engine functionalities by 
calling only step 1 and step 2 of the above from the application.
  - build custom applications by calling only step 1 above and by adding some 
custom systems and doing custom postOpenGLInit operations in the application.

### explanation of the problem
Radium engine initialization is spread across several classes and managed
in a non reliable way for the ones that want to use the Engine with or 
without openGL or with all the functionalities offered by the engine.

This feature request aims at defining simplified and reliable engine 
initialization from applications so that one can use all the functionalities 
offered by the engine with only a few line of code.

Lets recall for now how the Engine is initialized when used by a OpenGL graphical 
application that inherits from BaseApplication

1. The application instantiates and initializes the Engine singleton

```c++
    m_engine.reset( Ra::Engine::RadiumEngine::createInstance() );
    m_engine_initialize();
```
This initializes the all the Engine services able to work without openGL (mainly 
scene management services)

2. The application registers the base geometry system to the Engine

```c++
    m_engine->registerSystem(
        "GeometrySystem", new Ra::Engine::GeometrySystem, defaultSystemPriority );
``` 
This base system will populate the scene management services from any 
Ra::Core::Asset::FileData, e.g when loading datasets by using Radium::IO library.

3. The application creates a `MainWindowInterface` object that hold the main 
   application windows and the associated `Viewer`.
```c++
m_mainWindow.reset( factory.createMainWindow() );
m_mainWindow->show();
m_viwer = m_mainWindow->getViewer();
```   
Once the Viewer and its owning windows are created, the application configure 
the Qt signal/slot connexions so that the gui and the application can communicate.

One of this connection connect with the `Viewer::glInitialized();` signal to the 
`BaseApplication::initializeOpenGlPlugins` slot.  This signal is emitted by the 
`Viewer` once its OpenGL context is created and active.
But, and a part of the problem addressed by this feature request resides here, 
before emitting the signal, the viewer instantiate and initialize the 
ShaderProgramManager and populates this manager with several shaders used by 
the engine by calling `RadiumEngine::registerDefaultPrograms()`.

4. The application initialized some OpenGL dependant systems (e.g. Plugins)

5. Some scene services are also configured from the Renderer even if these 
   services are related to scene management (e.g. CameraManager, LightManager)

The current workflow make difficult and error-prone the integration of existing 
plugin (e.g the SkeletonAnimation Plugin) into the Engine as the plugin 
initialization must be split into several functions that must be called 
from several places. As plugins initialization follow the propose implementation 
of the feature request (3 functions : allocation, initialization without 
OpenGL, OpenGL) this new Engine initialisation procedure will ease integration 
of plugins into the engine and simplify its extension by new services.

**Comment by nmellado** [comment]
Thanks for the detailed issue.
Do you think that we could solve this by adding something like `RadiumEngine::onGLInitialized()`, which would be triggered by the application side (the one who creates the context). Then we need to centralize the initialization of all GL-related objects within this function.

**Comment by MathiasPaulin** [comment]
> Thanks for the detailed issue.
> Do you think that we could solve this by adding something like `RadiumEngine::onGLInitialized()`, which would be triggered by the application side (the one who creates the context). Then we need to centralize the initialization of all GL-related objects within this function.

Sure, but reminds that Engine is Qt independent. I'll propose very soon (a couple of hours) a PR that add a `RadiumEngine::initializeGL()` method to be called once the OpenGL context is created that corresponds to what I understand of your suggestion.

**Comment by nmellado** [comment]
Ok great.
I don't get why you emphasis that Engine is Qt independent, my suggestion does not involve any Qt mechanism. Will see with your proposal ;)

**Comment by MathiasPaulin** [comment]
> Ok great.
> I don't get why you emphasis that Engine is Qt independent, my suggestion does not involve any Qt mechanism. Will see with your proposal ;)

Don't worry about that, but in Radium, the methods called `onSomethingHappens` are related to Qt event management ;p

**Comment by nmellado** [comment]
I see, my bad.
