### ISSUE TITLE
Topological Mesh not detecting isolated singular vertices

### ISSUE THREAD

**Issue by Beafantles** [STORM-IRIT/Radium-Engine#687]
**OS:** Windows 10 64 bits version 2004
**Compiler:** Visual Studio 16 2019 (v16.8.5)
**CMake version:** 3.19.4
**Ninja version:** 1.10.2
**Radium-Engine version:** I used one of the latest version of Radium, from 9th February (commit 537caae).

I tried loading a non manifold mesh and converting it to a `Ra::Core::Geometry::TopologicalMesh`. I was expecting to see a warning as the mesh I was trying to convert into a `Ra::Core::Geometry::TopologicalMesh` instance was non manifold but there wasn't such warning displayed on the console.

Here's the code I used:

```cpp
#include <IO/deprecated/OBJFileManager.hpp>

int main(int argc, char *argv[])
{
    Ra::Core::Geometry::TriangleMesh mesh;
    Ra::IO::OBJFileManager           obj;

    obj.load(argv[1], mesh);
    Ra::Core::Geometry::TopologicalMesh topologicalMesh{ mesh };

    return 0;
}
```

I executed this program using the following command line arguments:
```
prog.exe non_manifold/simple.obj
```

Here's the content of `non_manifold/simple.obj`:
```obj
v 0   1   1
v 1   1   1
v 0.5 1   0
v 0.5 0.5 0.5
v 0   0   0
v 1   0   0
v 0.5 0   1


f 1 2 3
f 3 2 4
f 2 1 4
f 1 3 4
f 5 6 7
f 6 5 4
f 5 7 4
f 7 6 4
```
![meshlab_2C1RYfF030](https://user-images.githubusercontent.com/46332113/107528970-b2a24480-6bba-11eb-8d0b-76fd551b4776.png)

And here's the output of the program:
```
- 16:06:07 INFO: TopologicalMesh: load triMesh with 8 faces and 7 vertices.
- 16:06:07 WARNING: [TopologicalMesh] Skip badly sized attribute in_normal
```

`non_manifold/simple.obj` is a non manifold mesh which has only one topological singularity (vertice 4 is an isolated singular vertice). But this topological singularity doesn't seem to be detected.

**Comment by dlyr** [comment]
Well first of all, OBJLoader is deprecated, use with care.
The message states that normals are not set on you mesh (you should set dummy normals with the size of the vertices, even if the data is useless for you use, normals are mandatory for mesh).
Moreover, non manifold is detected at the OpenMesh level, and singular vertex is (should be) correctly handled, so no errors in your case.

**Comment by nmellado** [comment]
You mean that `OpenMesh` duplicates the non-manifold vertices ?

**Comment by dlyr** [comment]
Nope it's handled by the structures
["Ability to handle non-manifold vertices (like two faces meeting in only one vertex)."](https://www.graphics.rwth-aachen.de/media/openmesh_static/Documentations/OpenMesh-5.2-Documentation/a00012.html)

What is not handle is non manifold edge and faces, as well as degenerated faces.
Anther way to say it is that an halfedge belongs to at most one face (0 if boundary), and has exactly one opposite halfedge.

**Comment by nmellado** [comment]
The best thing you can do here is to loop over all vertices of the topological mesh once it is created, and detect non-manifold vertices.
