### ISSUE TITLE
Property not added when using default constructor of TopologicalMesh

### ISSUE THREAD

**Issue by martinbups** [STORM-IRIT/Radium-Engine#693]
The default constructor for `TopologicalMesh` does not add properties such as `m_wedgeIndexPph `. This property is used, for example here : https://github.com/STORM-IRIT/Radium-Engine/blob/627cbdb3106d755a5cebb8aaa909e32e156ccbed/src/Core/Geometry/TopologicalMesh.cpp#L913-L916
Hence a code like this :
```cpp
#include <Core/Geometry/TopologicalMesh.hpp>
int main( int argc, char* argv[] ) {
    Ra::Core::Geometry::TopologicalMesh topologicalMesh;
    Ra::Core::Geometry::TopologicalMesh::VertexHandle vhandle[3];
    Ra::Core::Geometry::TopologicalMesh::FaceHandle   fhandle;
    
    vhandle[0] = topologicalMesh.add_vertex(Ra::Core::Geometry::TopologicalMesh::Point( 1, -1, -1));
    vhandle[1] = topologicalMesh.add_vertex(Ra::Core::Geometry::TopologicalMesh::Point( 1, -1,  1));
    vhandle[2] = topologicalMesh.add_vertex(Ra::Core::Geometry::TopologicalMesh::Point(-1, -1,  1));
    
    std::vector<Ra::Core::Geometry::TopologicalMesh::VertexHandle>  face_vhandles;
    face_vhandles.clear();
    face_vhandles.push_back(vhandle[0]);
    face_vhandles.push_back(vhandle[1]);
    face_vhandles.push_back(vhandle[2]);
    fhandle = topologicalMesh.add_face(face_vhandles);
    
    std::cout << "faces: " << topologicalMesh.n_faces() << std::endl;
    
    topologicalMesh.request_face_status();
    topologicalMesh.delete_face( fhandle, false );
    std::cout << "faces: " << topologicalMesh.n_faces() << std::endl;
    return 0;
}

```
will lead to crashes when entering `delete_face`. Here is the output :
```
faces: 1
Segmentation fault (core dumped)
```

**Comment by dlyr** [comment]
Right, the current purpose of topological mesh is to be init with a Core::Mesh
We can easily add this functionality, but wedge "management" will need to be done on the user side. At least the proposed code should work without segfault.
I'll do it in an upcoming PR.

**Comment by nmellado** [comment]
Ok, in that case it I would prefer that we hide the default constructor, and replace the proposed code by something like:
```c++
TriangleMesh mesh;
// ....
// add vertices and faces
// ....
Ra::Core::Geometry::TopologicalMesh topologicalMesh (mesh);
```

**Comment by dlyr** [comment]
Well, in any case, the add_face do not add wedges, then the delete_face will produce an error message.
Client code as to call `setWedgeData` for the halfedges of the face.

**Comment by dlyr** [comment]
PR merged, check example [here](https://github.com/STORM-IRIT/Radium-Engine/blob/b5acbfcd90df7b612f0206b740bdd01d226ec890/tests/unittest/Core/topomesh.cpp#L762)
