### ISSUE TITLE
Some apps crash

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#694]
- The `RawShaderMaterial` app crashes at `GeometryComponent.inl`, line 127 because the Material does not exist
```
- 04:04:58 PM ERROR: Required material converter Ra::Engine::RawShaderMaterialData not found!
```

- The `integration_TinyPlyFileLoader` app crashes because the data are not found:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not open binary ifstream to path ../data/inputs/simple.ply
11:55:20: The program has unexpectedly finished.
```
Maybe this app is not meant to be installed/run along the others?

- Also, when running in Debug mode, I have these warnings/errors :
```
- 04:04:58 PM DEBUG: Invalid dirty bit notified on GridPrimitive
- 04:04:58 PM DEBUG: Invalid dirty bit notified on GridPrimitive
- 04:04:58 PM DEBUG: Invalid dirty bit notified on Frame Primitive
- 04:04:58 PM DEBUG: Invalid dirty bit notified on Frame 
```
Something might go wrong in the generation of the primitives.

**Comment by nmellado** [comment]
Todo:

- [ ] Find when regression occurred on RawShaderMaterial
- [ ] Fix RawShaderMaterial
- [ ] Fix unwanted installation of `integration` targets.

**Comment by nmellado** [comment]
Bug confirmed on latest release https://github.com/STORM-IRIT/Radium-Releases/releases/tag/2021.02.17
