### ISSUE TITLE
usage of [[deprecated]]

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#701]
There is several methods marked as `[[depreceated]]` while no other alternative are proposed yet.
For instance [here](https://github.com/STORM-IRIT/Radium-Engine/blob/6bd1877ac4010e6f986049c3805154dad7775f20/src/Engine/RadiumEngine.hpp#L115).

I think we can mark a warning in comments, but deprecated is better used only when an alternative is already available, to allow smooth transition. I prefer to have zero warning compilation on my code, and with theses "pre-deprecation" mark it is not possible (well actually I remove deprecation warning, but it is not a satisfactory option)

**Comment by MathiasPaulin** [comment]
I agree. I'm also tired of this numerous warnings when nothing can be done to remove them.

**Comment by dlyr** [comment]
Why the OFFFileManager is deprecated ? there is no comment about that in the file ...

**Comment by nmellado** [comment]
These loaders (off and obj) do not fit to the IO package, that’s all.

**Comment by dlyr** [comment]
Is there any associate todo ? issue ? or we leave it as is ... I would like to do something but I don't know what.

**Comment by nmellado** [comment]
Yes,this one (had been closed by automation): https://github.com/STORM-IRIT/Radium-Engine/issues/362

**Comment by dlyr** [comment]
Ok I add a reference in the code to the issue, and removed deprecated tag.
