### ISSUE TITLE
KeyMapping manager add action should not automagically save

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#704]
As pointed out in #702 
In the current implementation, KeyMappingManager::addAction allows client code to add action and its configuration (mouse, key, modifiers) dynamically to the manager during run time.
This feature is to have default behavior in case your settings are not configured for a given action, but it also save directly the conf file.
I think instead of saving the conf file directly, we can have a bool to state that the configuration is modified wrt the file.
The application could check this flag before exit, or when loading a new file, to ask the user if he wants to save the modified configuration.

**Comment by nmellado** [comment]
Fixed by #776.
