### ISSUE TITLE
Replace Entity pointers by Entity index and remove all name-based relationships

### ISSUE THREAD

**Issue by cmourglia** [STORM-IRIT/Radium-Engine#71]
Some Engine components and "client" code use Entity\* instead of indices. This should be replaced by EntityIdx and a request to the EntityManager to avoid uses of invalid pointers.

**Comment by louen** [comment]
what about  components ?

**Comment by louen** [comment]
We should avoid storing objects by name in a map and prefer unique indices.

**Comment by MathiasPaulin** [comment]
This issue is too imprecise to understand the problem and fix it. Reopen with a clearer description of the issue.
