### ISSUE TITLE
Question/Bug Non-Manifold cube when a vertex is collapsed

### ISSUE THREAD

**Issue by MatheoDumont** [STORM-IRIT/Radium-Engine#724]
I've used HelloRadium for a small implementation to simplify a mesh using Radium Topological Meshs, but after collapsing a vertex i get a non-manifold cube with a hole.

```cpp

int main(int argc, char *argv[])
{

    //! [Creating the application]
    Ra::Gui::BaseApplication app(argc, argv);
    app.initialize(Ra::Gui::SimpleWindowFactory{});

    //! [Create the engine entity for the Mesh]
    auto e = app.m_engine->getEntityManager()->createEntity("Mesh");


    auto cube = Ra::Core::Geometry::makeSharpBox({0.1f, 0.1f, 0.1f});

    auto handle = cube.addAttrib("in_color",
                                 Ra::Core::Vector4Array(cube.vertices().size(), Ra::Core::Utils::Color::Green()));
    auto &attrib = cube.getAttrib(handle);
    auto &buf = attrib.getDataWithLock();
    buf[0] = Ra::Core::Utils::Color::Black();
    attrib.unlock();

    TopologicalMesh topo_mesh = TopologicalMesh(cube);

    topo_mesh.collapseWedge(topo_mesh.halfedge_handle(topo_mesh.face_handle(0)));
    topo_mesh.garbage_collection();

    auto refined_mesh = topo_mesh.toTriangleMeshFromWedges();
    std::cout << refined_mesh.vertices().size() << std::endl;

    //! [Create a geometry component with the cube]
    auto c =
        new Ra::Engine::Scene::TriangleMeshComponent("Cube Mesh", e, std::move(refined_mesh), nullptr);
    // !! ----
    //! [Register the entity/component association to the geometry system ]
    auto geometrySystem = app.m_engine->getSystem("GeometrySystem");

    geometrySystem->addComponent(e, c);

    //! [Tell the window that something is to be displayed]
    app.m_mainWindow->prepareDisplay();

    return app.exec();
}
```
And it gives this :
![nonmanifold](https://user-images.githubusercontent.com/29271028/112873479-f812c680-90c1-11eb-8863-1610897ff5c3.png)
Maybe i am missing something to do this right.

(i hope its okay, maybe im just bothering you with my questions)

**Comment by dlyr** [comment]
I think this bug is "normal" on current master.
You can first check to use collapse instead of collapseWedge, and toTriangleMesh, just to check the topology is ok.
Then you could you try [dlyr/quad-mesh-round2 ](https://github.com/dlyr/Radium-Engine/tree/quad-mesh-round2) ?
On this branch toTriangleMeshFromWedges(); is renamed toTrianglMesh, since wedge is the only alternative (and collapse is also renamed if I remeber well).

And sure it's ok to ask questions and show potential bug. Feel free to update once tested, or ask for details if my answer is not clear enough.

**Comment by MatheoDumont** [comment]
Thanks i'll try !

**Comment by nmellado** [comment]
@MatheoDumont, PR #719 (branch [quad-mesh-round2](https://github.com/dlyr/Radium-Engine/tree/quad-mesh-round2) ) is about to be merged in `master`.

**Comment by dlyr** [comment]
Could we wait for the test before merging ?

**Comment by nmellado** [comment]
Modifications poussée dans `master`. @MatheoDumont let us know if it fixes your problem.

**Comment by dlyr** [comment]
In the new version, wedge is the only option, so you could call `collapse` directly (the `Wedge` version is a deprecated alias).
These features are in active development, so do not hesitate to open issue like this one so we can test and improve stability.

**Comment by MatheoDumont** [comment]
i don't have pulled yet, but using `collapse()` and `fromTriangleMesh()` instead solved it.

**Comment by dlyr** [comment]
Ok, but these correspond to the old "attributes on halfedge" way of handling wedges.
So the medged PR might recreate the issue.

**Comment by MatheoDumont** [comment]
do i need to reinstall Radium after having pulled ?

**Comment by dlyr** [comment]
If you use it as an external library, yes, pull, recompile, (delete installation bundle to remove old includes) reinstall, rebuild you application.

**Comment by dlyr** [comment]
If you use the HelloRadium directly in radium build tree, just recompile.

**Comment by MatheoDumont** [comment]
I re-installed Radium with the latest version and it works fine, thanks for your help !
