### ISSUE TITLE
Accelerated geometry data structures 

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#77]
BVH, Kd-Tree, etc. (Or use some from a library to avoid screwing it up and having good performance.)
This wil lbe usefull for having a raytracer.

**Comment by Zouch** [comment]
Do you know some libraries that do this kind of stuff ?

2016-02-25 19:44 GMT+01:00 Valentin Roussellet <notifications@github.com>:

**Comment by Yenapas** [comment]
Libraries, I don't know.
But I know various code (GPL or not) for that like Embree, PBRTv3, and some
similar stuff.


2016-02-25 20:18 GMT+01:00 Charly Mourglia <notifications@github.com>:
