### ISSUE TITLE
Test IO/VolumesLoader fails when compiled with Scalar=double

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#855]
Error logs: https://github.com/STORM-IRIT/Radium-Engine/actions/runs/1709898742

The problems seems to come from the fact that volume files are stored in `float`: numbers are loaded from files, casted to `double`, and then compared to `double` constants with an epsilon value in `double`. This test is very likely to fail and would require a `float` epsilon value.

**Comment by dlyr** [comment]
We can increase the parameter 
[espilonBoostFactor](https://storm-irit.github.io/Radium-Engine/namespaceRa_1_1Core_1_1Math.html#a46540d56930b4c1ff3b115872cde4893)
Let's first check the values compared, maybe there is another bug.
