### ISSUE TITLE
Add example: load and display texture on quad

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#887]
There is currently no example showing how to load a texture from a file, can we add a single-file demo doing that ?

**Comment by MathiasPaulin** [comment]
Not sure to understand what you're asking for. The texture manager offers all what is needed for that. The documentation says how to load a texture from a file (even if the doc could be improved in its form and content, the main objectives are covered). See [getOrLoadTexture](https://storm-irit.github.io/Radium-Engine/release-candidate/classRa_1_1Engine_1_1Data_1_1TextureManager.html#a59b5fb2a6870ae9423829a3401e4b4b6), [loadTexture](https://storm-irit.github.io/Radium-Engine/release-candidate/classRa_1_1Engine_1_1Data_1_1TextureManager.html#a5680332e080cccaac9d0fe9632a8da0f) and [loadTextureImage](https://storm-irit.github.io/Radium-Engine/release-candidate/classRa_1_1Engine_1_1Data_1_1TextureManager.html#ab744921bc126b356965047f2d2945ee1)

**Comment by dlyr** [comment]
closed by #890
