### ISSUE TITLE
Open-source Radium Engine

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#89]
We should get in the clear around the licence of  the radium engine if possible.

AFAIK all the external code we use is compatible with most open source licences.
- [ ] pick a suitable licence (MPL ? LGPL ?)
- [ ] clear legal issues from IRIT
- [ ] get all contributors to agree to release their code

**Comment by louen** [comment]
GPL is not considered because plugins would have to be GPL'd as well, but LGPL is perfectly sensible. (Although some files still might be subject to the MPL).

**Comment by nmellado** [comment]
I usually choose the MPLv2 for my projects (https://www.mozilla.org/en-US/MPL/2.0/).
It is simple and convenient for industrial transfers.

**Comment by nmellado** [comment]
FYI: https://help.github.com/articles/licensing-a-repository/
No license set by default.

**Comment by nmellado** [comment]
FYI: According to recent discussions IRL, we may use a dual-licensing solution to cover both commercial and research/education uses.

**Comment by nmellado** [comment]
Radium is now licensed under APACHE 2.0.
