### ISSUE TITLE
Weird formatting of documentation with doxygen 1.9.3

### ISSUE THREAD

**Issue by MathiasPaulin** [STORM-IRIT/Radium-Engine#898]
The radium documentation, generated using doxygen 1.9.3, suffers from strange organisation in the navigation menu (left panel).
Here is a screenshot of the main page, with documentation compiled with doxygen 1.9.3
![Capture d’écran 2022-04-05 à 19 11 49](https://user-images.githubusercontent.com/11328578/161812596-c2039a30-4573-4367-bbe9-ac997ef67b83.png)

The same documentation (from https://storm-irit.github.io/Radium-Engine/release-candidate/) generated with doxygen 1.8.17, has a well organized menu 
![Capture d’écran 2022-04-05 à 19 14 37](https://user-images.githubusercontent.com/11328578/161813038-240ad082-7895-4d21-a9ee-5915e7797d00.png)

**Comment by nmellado** [comment]
It looks like the page hierarchy is lost, and all pages are listed flat. Am I right ?

**Comment by dlyr** [comment]
Quick fix : use doxygen 1.9.1
I check what's happening, it's not the first time doxygen screwup with menu.

**Comment by dlyr** [comment]
I confirm it's broken even on simple doxygen md page hierarchy, nothing related to Radium. Please report the issue to upstream doxygen.

**Comment by dlyr** [comment]
Issue opened on doxygen side https://github.com/doxygen/doxygen/issues/9254
I close this one.
