### ISSUE TITLE
Preformances question

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#911]
I open this issue to continue the discussion started in PR #900 , since I think it's out of scope of the PR.

[compareTest.zip](https://github.com/STORM-IRIT/Radium-Engine/files/8498307/compareTest.zip)

_Originally posted by @hiergaut in https://github.com/STORM-IRIT/Radium-Engine/pull/900#discussion_r851519207_

**Comment by dlyr** [comment]
I had to change slightly the code to make it run on my mac.
Add #include <random> and #include <algorithm>
use shuffle instead of random_shuffle. I'll post the updated test file here.
Nevertheless, I think we should enhance the test with :
- check for failed test.
- only consider std::string as left hand side of the test.

**Comment by hiergaut** [comment]
I can't see your contribution (#include ?), so I update with my own one (with fixed shuffle + failed test + only str test).
[compareTest.zip](https://github.com/STORM-IRIT/Radium-Engine/files/8512140/compareTest.zip)

**Comment by hiergaut** [comment]
[string == enum attrib constexpr char array] duration =_____________________21.8722 ns,    (0%)	reference	
 [string == enum attrib constexpr char array in inline function] duration =________24.4298 ns,    (11.6935%)	pr #900	
 [string == enum attrib const char array] duration =_________________________22.0033 ns,    (0.599559%)	
 [enum class + bool operator==(string, MeshAttrib)] duration =________________21.8114 ns,    (-0.277664%)	
 [string hash == hash array] duration =___________________________________22.9654 ns,    (4.99805%)	
 [map[string] == MeshAttrib] duration =___________________________________46.8748 ns,    (114.313%)	slowest
 [string == constexpr string view array of MeshAttrib] duration =_______________18.1577 ns,    (-16.9825%)	fastest
 [magic enum : string == magic::enum_name(MeshAttrib)] duration =___________18.4862 ns,    (-15.481%)	
[magic enum : magic::enum_cast\<MeshAttrib\>(string) == MeshAttrib] duration =__39.8988 ns,    (82.4179%)

**Comment by dlyr** [comment]
Thanks to your proposal, I just test this 
```cpp
inline const std::string& getAttribName( MeshAttrib index ) noexcept {
    static std::string g_attribNameString[MeshAttrib::MAX_DATA] = { "in_position",
                                                                    "in_normal",
                                                                    "in_tangent",
                                                                    "in_bitangent",
                                                                    "in_texcoord",
                                                                    "in_color",
                                                                    "in_weight",
                                                                    "in_weight_idx" };
    return g_attribNameString[index];
}
```
Which is on par with fastet alternative (I do not consider magic_enum since it modifies enum names, this enum is here to decorelate attrib names from the enum, otherwise, we can simply keep in_normal for normals ...)

**Comment by hiergaut** [comment]
[string == enum attrib constexpr char array] duration =    ___________________33.2458 ns,    (0%)	reference	
[string == enum attrib constexpr char array in inline function] duration =  ______  37.6642 ns,    (13.2899%)	pr #900	
[string == enum attrib const ref string array in inline function] duration =     _____23.482 ns,    (-29.3687%)	david proposition
[string == enum attrib const char array] duration =   ______________________ 33.7501 ns,    (1.5168%)	
[enum class + bool operator==(string, MeshAttrib)] duration =   _____________ 33.3026 ns,    (0.170726%)	
[string hash == hash array] duration =    _______________________________30.4444 ns,    (-8.42643%)	
[map[string] == MeshAttrib] duration =  _______________________________  58.5475 ns,    (76.1048%)	slowest
[string == constexpr string view array of MeshAttrib] duration =   ____________ 23.4026 ns,    (-29.6074%)	
[magic enum : string == magic::enum_name(MeshAttrib)] duration =   ________ 23.1997 ns,    (-30.2177%)	fastest
[magic enum : magic::enum_cast<MeshAttrib>(string) == MeshAttrib] duration = 51.3347 ns,    (54.4095%)

**Comment by hiergaut** [comment]
with david's proposal, we increase the performance of the enum comparison with a string by 40% compared to those we currently have on the pr #900

**Comment by hiergaut** [comment]
it's not the most efficient, but using string view implies C++ standard 17

**Comment by dlyr** [comment]
I close the issue, the current version is fine enough.
