### ISSUE TITLE
Write radium programmer manual

### ISSUE THREAD

**Issue by cmourglia** [STORM-IRIT/Radium-Engine#92]
Could it be interesting to keep up to date a wiki page where we list interesting radium features ? 
It's easy to not pay attention to a commit and miss features that might help you (i.e. geometry processing algorithms, debug stuff (drawprimitives, debug render), raytracing, acceleration structures, etc)

**Comment by louen** [comment]
So what you want has a name.... It's called a manual. And  we must write it.

**Comment by Zouch** [comment]
We could just begin by writing the features, without explaining them (or
just a bit of code, if needed for clarity). That might help writing man
pages and not forgetting everything later on

2016-03-23 15:50 GMT+01:00 Valentin Roussellet <notifications@github.com>:

**Comment by MathiasPaulin** [comment]
Radium documentation contains programming guide for main components. see PR Doxygen documentation update #355 for more.
