### ISSUE TITLE
${RadiumHeadless_VERSION} is not set when configure Radium

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#927]
`tests/ExampleApps/HeadlessDemo/CMakeLists.txt` refers `${RadiumHeadless_VERSION}` which is not set
cmake output is 
`-- [Tests] Configuring demo application HeadlessDemo with RadiumHeadless  and Radium 1.2.21`
(while the RadiumHeadless_VERSION is expected after RadiumHeadless ^^)

**Comment by MathiasPaulin** [comment]
Closed by PR #934
