### ISSUE TITLE
Remove config time external build

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#933]
The old behavior to compile external at Radium-Engine configure time becomes less usable and prone to user error.
I propose to remove totally this feature, hence user have to first compile the externals, then provides the needed cmake variables to use precompiled externals

To this end the external installs process should create (or print the content of) a configuration file similar to what is state in the doc.

**Comment by hiergaut** [comment]
why not use sub-modules for the externals?

**Comment by dlyr** [comment]
Current build external first uses a CMakeLists that fetch externals, it's like submodules, but have some advantages (like patch) I think.
