### ISSUE TITLE
Rendering is done between processing user inputs and tasks 

### ISSUE THREAD

**Issue by bangles** [STORM-IRIT/Radium-Engine#95]
Solution: Render the scene after processing the tasks. Will cause some issues if rendering is done in a separate thread.

**Comment by louen** [comment]
The question is : is it possible to render on a separate thread ?
If we want multithreaded rendering we could make it a task forced on the main thread instead...

**Comment by Zouch** [comment]
Rendering on a separate thread was just destroying the perf if I remember
correctly. I don't know if it was a Qt issue or not, but I strongly think
so.

2016-06-21 13:53 GMT+02:00 Valentin Roussellet <notifications@github.com>:

**Comment by louen** [comment]
Yes because you need to transfer the OpenGL context from the main thread to the render thread, which takes time.

However if rendering is done as a task forced on the main thread *while* the tasks are active we could grab a few milisecs without paying that cost.

**Comment by Zouch** [comment]
We could indeed launch the tasks, then the rendering, and finally wait for the tasks to finish. But this implies double buffering everything that might be modified by a task and impact rendering. 
Maybe we could find a way to automatize this a little bit.

**Comment by MathiasPaulin** [comment]
Scene is rendered after the tasks are done. No multithreaded rendering is planed. Close this issue.
