### ISSUE TITLE
How to run Headless on remote ci

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#971]
If I run Headless example thru ssh (on localhost, where it works fine directly)
I get
```{.bash}
./HeadlessExample
OpenGL context creation failed. Terminate execution.
OpenGLContext::GLFW error -- 0x10008: X11: The DISPLAY environment variable is missing
 ```
Do I miss something ?

**Comment by MathiasPaulin** [comment]
you miss something. 
Even if headless do not require a physical display, on Linux, a X11 server is required to obtain an OpenGL context. So, to run the headless example on the linux-CI, and as already discussed in the PR 
https://github.com/STORM-IRIT/Radium-Engine/pull/958#discussion_r915480535 #958, discussed AFK and shown in our private gitlab CI, you just need to do (on github CI) : `xvfb-run -a examples/HeadlessExample/HeadlessExample`
The linux environment on the github CI already contains the package xvfb. For our docker image used on gitlab, I'm not sure this package is installed (but it can be by the CI script) but will verify ASAP.

**Comment by dlyr** [comment]
Any guess how to do the same on macos and windows ci ?

**Comment by MathiasPaulin** [comment]
> Any guess how to do the same on macos and windows ci ?

No need for an X11 server on  macos or windows ^^

As far as I was able to test, on macos, just run the program as usual. I think it will be the same on windows.

**Comment by dlyr** [comment]
CI fails with: 
windows:
```
45/46 Test #45: integration_HeadlessExample .......................***Failed    0.67 sec
OpenGLContext::GLFW error -- 0x10006: WGL: The driver does not appear to support OpenGL
OpenGL context creation failed. Terminate execution.
```
mac
```
OpenGLContext::GLFW error -- 0x10009: NSGL: Failed to find a suitable pixel format
OpenGL context creation failed. Terminate execution.
```
see https://github.com/STORM-IRIT/Radium-Engine/runs/7369521486?check_suite_focus=true
Last CI works, since I added check for UNIX in cmake to setup test with xvfb-run

**Comment by dlyr** [comment]
After some tests, glfw context need an operating windows system, one solution might be to use egl context, e.g.
https://github.com/NVIDIA-developer-blog/code-samples/blob/master/posts/egl_OpenGl_without_Xserver/tinyegl.cc

**Comment by MathiasPaulin** [comment]
As headless now support EGL that allows to compute image on remote hardware (well only on Linux in CI or through ssh), is this issue still alive?
